#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import io
src = io.open('../pdf/lector-del-cielo_EN.html', encoding='utf-8').read()
R = []
def rep(a,b): R.append((a,b))

# ---- section 7 ----
rep('<h2 id="7-sincronía-lunar-solar-metón-octaeteris-y-calendario-islámi">7. Sincronía lunar-solar: Metón, octaeteris y calendario islámico</h2>', '<h2 id="7-sincronía-lunar-solar-metón-octaeteris-y-calendario-islámi">7. Lunar–solar synchrony: Meton, octaeteris, and the Islamic calendar</h2>')
rep('<p><strong>Constantes (días):</strong> mes sinódico = 29,530589; mes dracónico = 27,212221; mes anomalístico = 27,554550; año trópico = 365,24219; año de eclipses = 346,620083.</p>',
    '<p><strong>Constants (days):</strong> synodic month = 29.530589; draconic month = 27.212221; anomalistic month = 27.554550; tropical year = 365.24219; eclipse year = 346.620083.</p>')
rep('<p>El año trópico contiene <strong>365,24219 / 29,530589 = 12,36827 meses sinódicos</strong>. Ningún número entero de lunaciones cierra el año solar; de ahí todos los calendarios lunisolares necesitan <strong>intercalación</strong>.</p>',
    '<p>The tropical year contains <strong>365.24219 / 29.530589 = 12.36827 synodic months</strong>. No integer number of lunations closes the solar year; hence all lunisolar calendars require <strong>intercalation</strong>.</p>')
rep('<th>ciclo</th><th>años</th><th>lunaciones</th><th>cálculo</th><th>error</th>', '<th>cycle</th><th>years</th><th>lunations</th><th>calculation</th><th>error</th>')
rep('<td>Metón</td><td>19</td><td>235</td><td>235×29,5306 = 6939,69 d ; 19×365,2422 = 6939,60 d</td><td><strong>0,087 d</strong></td>', '<td>Meton</td><td>19</td><td>235</td><td>235×29.5306 = 6939.69 d ; 19×365.2422 = 6939.60 d</td><td><strong>0.087 d</strong></td>')
rep('<td>Calipo</td><td>76</td><td>940</td><td>940×29,5306 = 27758,75 d ; 76×365,2422 = 27758,41 d</td><td>0,35 d</td>', '<td>Callippus</td><td>76</td><td>940</td><td>940×29.5306 = 27758.75 d ; 76×365.2422 = 27758.41 d</td><td>0.35 d</td>')
rep('<td>Octaeteris</td><td>8</td><td>99</td><td>99×29,5306 = 2923,53 d ; 8×365,2422 = 2921,94 d</td><td>1,59 d</td>', '<td>Octaeteris</td><td>8</td><td>99</td><td>99×29.5306 = 2923.53 d ; 8×365.2422 = 2921.94 d</td><td>1.59 d</td>')
rep('<p><strong>El calendario hebreo (metónico)</strong> inserta <strong>7 meses intercalares en 19 años</strong>: 12 años comunes (12 meses) + 7 años bisiestos (13 meses) = 12×12 + 7×13 = <strong>144 + 91 = 235</strong> lunaciones = 19 años solares. (Véase §14 sobre el 144.)</p>',
    '<p><strong>The Hebrew (metonic) calendar</strong> inserts <strong>7 intercalary months in 19 years</strong>: 12 common years (12 months) + 7 leap years (13 months) = 12×12 + 7×13 = <strong>144 + 91 = 235</strong> lunations = 19 solar years. (See §14 on 144.)</p>')
rep('<p><strong>El calendario islámico (hijri)</strong> es <strong>lunar puro, sin intercalación</strong> (Qur\'an 9:36–37 prohíbe el <em>nasīʾ</em>): 12 sinódicos = 354,367 d; deriva <strong>10,875 d/año</strong> respecto al solar.</p>',
    '<p><strong>The Islamic (hijri) calendar</strong> is <strong>pure lunar, without intercalation</strong> (Qur\'an 9:36–37 forbids <em>nasīʾ</em>): 12 synodics = 354.367 d; it drifts <strong>10.875 d/year</strong> relative to the solar.</p>')
rep('<ul><li>33 años islámicos: 33 × 10,875 = <strong>358,9 d ≈ 1 año solar</strong> (365 d) → el año hijri vuelve a la misma estación cada <strong>~33 años</strong>.</li><li>Verificación: 33×354,367 = 11 694,1 d ; 32×365,2422 = 11 687,8 d ; Δ = 6,4 d.</li></ul>',
    '<ul><li>33 Islamic years: 33 × 10.875 = <strong>358.9 d ≈ 1 solar year</strong> (365 d) → the hijri year returns to the same season every <strong>~33 years</strong>.</li><li>Verification: 33×354.367 = 11 694.1 d ; 32×365.2422 = 11 687.8 d ; Δ = 6.4 d.</li></ul>')

# ---- section 8 ----
rep('<h2 id="8-el-19-metón-saros-y-la-basmala">8. El 19: Metón, Saros y la basmala</h2>', '<h2 id="8-el-19-metón-saros-y-la-basmala">8. The 19: Meton, Saros, and the basmala</h2>')
rep('<p>El número <strong>19</strong> aparece en tres registros distintos que son, sin embargo, <strong>el mismo arco lunar</strong>:</p>',
    '<p>The number <strong>19</strong> appears in three distinct registers that are, however, <strong>the same lunar arc</strong>:</p>')
rep('<p><strong>1. Metón (calendario):</strong> 19 años trópicos = 235 lunaciones (sección 7; Δ 0,087 d).</p>',
    '<p><strong>1. Meton (calendar):</strong> 19 tropical years = 235 lunations (section 7; Δ 0.087 d).</p>')
rep('<p><strong>2. Saros (eclipses):</strong> el año de eclipses (346,620083 d) es el tiempo que tarda el Sol en volver al nodo lunar. <strong>19 años de eclipse = 19 × 346,620083 = 6585,78 d</strong>, y el Saros = 223 sinódicos = 6585,32 d → <strong>Δ = 0,46 d</strong>. El Saros es casi exactamente 19 años de eclipse.</p>',
    '<p><strong>2. Saros (eclipses):</strong> the eclipse year (346.620083 d) is the time it takes the Sun to return to the lunar node. <strong>19 eclipse years = 19 × 346.620083 = 6585.78 d</strong>, and the Saros = 223 synodics = 6585.32 d → <strong>Δ = 0.46 d</strong>. The Saros is almost exactly 19 eclipse years.</p>')
rep('<p><strong>3. Basmala coránica:</strong> «بسم الله الرحمن الرحيم» = <strong>19 letras</strong>; el Corán tiene 114 azoras = <strong>6×19</strong>. (La «hipótesis del 19» de R. Khalifa es una lectura numerológica del Corán; los hechos aritméticos —19 letras de la basmala, 114 = 6×19— son verificables, su interpretación codificadora es discutida.)</p>',
    '<p><strong>3. Quranic basmala:</strong> «بسم الله الرحمن الرحيم» = <strong>19 letters</strong>; the Quran has 114 suras = <strong>6×19</strong>. (R. Khalifa\'s "19 hypothesis" is a numerological reading of the Quran; the arithmetic facts —19 letters of the basmala, 114 = 6×19— are verifiable; its encoding interpretation is disputed.)</p>')
rep('<p><strong>Verificación astronómica del Saros (astronomy-engine):</strong> eclipse solar global del 2023-04-20 (pico 04:16:42 UT); añadiendo 223 sinódicos (6585,32 d) se obtiene el 2041-04-30 (pico 11:50:53 UT); Δ real = <strong>6585,32 d</strong> = el teórico. Ambos pertenecen a la misma serie saros.</p>',
    '<p><strong>Astronomical verification of the Saros (astronomy-engine):</strong> global solar eclipse of 2023-04-20 (peak 04:16:42 UT); adding 223 synodics (6585.32 d) yields 2041-04-30 (peak 11:50:53 UT); real Δ = <strong>6585.32 d</strong> = the theoretical. Both belong to the same saros series.</p>')
rep('<blockquote>El 19 une el calendario (Metón), el eclipse (Saros = 19 años de eclipse) y la numerología coránica (basmala de 19 letras). Es el <strong>número de la sincronía lunar</strong>.</blockquote>',
    '<blockquote>The 19 unites the calendar (Meton), the eclipse (Saros = 19 eclipse years), and the Quranic numerology (basmala of 19 letters). It is the <strong>number of lunar synchrony</strong>.</blockquote>')

# ---- section 9 ----
rep('<h2 id="9-eclipses-ciclos-factorización-y-la-cuestión-37-73">9. Eclipses: ciclos, factorización y la cuestión 37 / 73</h2>', '<h2 id="9-eclipses-ciclos-factorización-y-la-cuestión-37-73">9. Eclipses: cycles, factorization, and the 37 / 73 question</h2>')
rep('<h3 id="9-1-ciclos-eclipsales-y-su-factorización">9.1 Ciclos eclipsales y su factorización</h3>', '<h3 id="9-1-ciclos-eclipsales-y-su-factorización">9.1 Eclipse cycles and their factorization</h3>')
rep('<p>Un ciclo eclipsal es un entero <em>N</em> de meses sinódicos cercano a un entero de meses dracónicos (retorno al nodo). Tabla canónica:</p>',
    '<p>An eclipse cycle is an integer <em>N</em> of synodic months close to an integer of draconic months (return to the node). Canonical table:</p>')
rep('<th>ciclo</th><th>N (sinódicos)</th><th>días</th><th>N dracónicos</th><th>factorización de N</th>', '<th>cycle</th><th>N (synodics)</th><th>days</th><th>N (draconics)</th><th>factorization of N</th>')
rep('<td>Octon</td><td>47</td><td>1387,94</td><td>51</td><td><strong>47</strong> (primo)</td>', '<td>Octon</td><td>47</td><td>1387.94</td><td>51</td><td><strong>47</strong> (prime)</td>')
rep('<td>Hepton</td><td>87</td><td>2569,16</td><td>94</td><td>3 × 29</td>', '<td>Hepton</td><td>87</td><td>2569.16</td><td>94</td><td>3 × 29</td>')
rep('<td>Octaeteris</td><td>99</td><td>2923,53</td><td>107</td><td>3² × 11</td>', '<td>Octaeteris</td><td>99</td><td>2923.53</td><td>107</td><td>3² × 11</td>')
rep('<td>Tritos</td><td>135</td><td>3986,63</td><td>147</td><td>3³ × 5</td>', '<td>Tritos</td><td>135</td><td>3986.63</td><td>147</td><td>3³ × 5</td>')
rep('<td>Sar</td><td>177</td><td>5226,91</td><td>192</td><td>3 × 59</td>', '<td>Sar</td><td>177</td><td>5226.91</td><td>192</td><td>3 × 59</td>')
rep('<td><strong>Saros</strong></td><td><strong>223</strong></td><td><strong>6585,32</strong></td><td><strong>242</strong></td><td><strong>223 (primo)</strong></td>', '<td><strong>Saros</strong></td><td><strong>223</strong></td><td><strong>6585.32</strong></td><td><strong>242</strong></td><td><strong>223 (prime)</strong></td>')
rep('<td>Inex</td><td>358</td><td>10 571,95</td><td>389</td><td>2 × 179</td>', '<td>Inex</td><td>358</td><td>10 571.95</td><td>389</td><td>2 × 179</td>')
rep('<td>Exeligmos</td><td>669</td><td>19 755,96</td><td>726</td><td>3 × 223</td>', '<td>Exeligmos</td><td>669</td><td>19 755.96</td><td>726</td><td>3 × 223</td>')
rep('<td>Calipo</td><td>940</td><td>27 758,75</td><td>1020</td><td>2² × 5 × 47</td>', '<td>Callippus</td><td>940</td><td>27 758.75</td><td>1020</td><td>2² × 5 × 47</td>')
rep('<p>Saros = 223 sinódicos = 242 dracónicos (6585,36 d) = 239 anomalísticos (6585,54 d) — triple coincidencia que hace que un eclipse se repita con geometría casi idéntica cada 18,03 años.</p>',
    '<p>Saros = 223 synodics = 242 draconics (6585.36 d) = 239 anomalistics (6585.54 d) — a triple coincidence that makes an eclipse repeat with almost identical geometry every 18.03 years.</p>')
rep('<h3 id="9-2-aparecen-37-o-73">9.2 ¿Aparecen 37 o 73?</h3>', '<h3 id="9-2-aparecen-37-o-73">9.2 Do 37 or 73 appear?</h3>')
rep('<p><strong>Cálculo directo:</strong> se comprueba la divisibilidad de los 10 ciclos canónicos (y sus dobles/triples) entre 37 y 73:</p>',
    '<p><strong>Direct calculation:</strong> the divisibility of the 10 canonical cycles (and their doubles/triples) by 37 and 73 is checked:</p>')
rep('<p><strong>37 × 73 = 2701 = Génesis 1:1.</strong> Ningún ciclo eclipsal canónico es divisible por 37 o por 73. Los primos estructurales de los eclipses son <strong>19</strong> (año de eclipse ×19 ≈ Saros), <strong>47</strong> (Octon; factor del Meton) y <strong>223</strong> (Saros). </p>',
    '<p><strong>37 × 73 = 2701 = Genesis 1:1.</strong> No canonical eclipse cycle is divisible by 37 or by 73. The structural primes of eclipses are <strong>19</strong> (eclipse year ×19 ≈ Saros), <strong>47</strong> (Octon; factor of Meton), and <strong>223</strong> (Saros). </p>')
rep('<p><strong>El único contacto de 73 con los eclipses es estadístico, no estructural:</strong> una serie saros contiene entre ~70 y ~86 eclipses a lo largo de ~1226–1550 años (valor medio ~72–73, sin número fijo). Es un recuento, no un periodo.</p>',
    '<p><strong>The only contact of 73 with eclipses is statistical, not structural:</strong> a saros series contains between ~70 and ~86 eclipses over ~1226–1550 years (mean ~72–73, with no fixed number). It is a count, not a period.</p>')
rep('<p><strong>Aclaración sobre el ciclo nodal (18,6 a).</strong> Se ha sostenido que la precesión nodal lunar (18,613 años) contiene «37 estaciones de eclipse». El cálculo lo desmiente: el periodo nodal = 18,613 × 365,2422 = <strong>6798,24 d</strong>; la estación de eclipse = año de eclipses/2 = 346,6201/2 = <strong>173,310 d</strong>; el cociente = 6798,24 / 173,310 = <strong>39,23 estaciones</strong> (≈ 39), no 37. El número que sí cierra es <strong>38</strong>: 38 × 173,310 = 6585,78 d = 19 años de eclipse = <strong>Saros</strong>. Así, 37 no aparece ni en el ciclo nodal.</p>',
    '<p><strong>Clarification on the nodal cycle (18.6 y).</strong> It has been held that the lunar nodal precession (18.613 years) contains "37 eclipse seasons". The calculation refutes this: the nodal period = 18.613 × 365.2422 = <strong>6798.24 d</strong>; the eclipse season = eclipse year/2 = 346.6201/2 = <strong>173.310 d</strong>; the quotient = 6798.24 / 173.310 = <strong>39.23 seasons</strong> (≈ 39), not 37. The number that does close is <strong>38</strong>: 38 × 173.310 = 6585.78 d = 19 eclipse years = <strong>Saros</strong>. Thus 37 appears neither in the nodal cycle.</p>')
rep('<blockquote><strong>Conclusión demostrada.</strong> 37 y 73 son los factores de <strong>Génesis 1:1</strong> (2701), no números de eclipse. No aparecen como factores de ningún ciclo eclipsal ni en el recuento del ciclo nodal (~39, no 37). Los primos estructurales de los eclipses son 19, 47 y 223. <strong>37 y 73 sí encajan, en cambio, en el año solar</strong> (§9.4).</blockquote>',
    '<blockquote><strong>Demonstrated conclusion.</strong> 37 and 73 are the factors of <strong>Genesis 1:1</strong> (2701), not eclipse numbers. They do not appear as factors of any eclipse cycle nor in the count of the nodal cycle (~39, not 37). The structural primes of eclipses are 19, 47, and 223. <strong>37 and 73 do fit, by contrast, into the solar year</strong> (§9.4).</blockquote>')
rep('<h3 id="9-3-correlación-días-génesis-eclipses-test-empírico">9.3 Correlación días-Génesis / eclipses (test empírico)</h3>', '<h3 id="9-3-correlación-días-génesis-eclipses-test-empírico">9.3 Genesis-days / eclipses correlation (empirical test)</h3>')
rep('<p>Se contrastaron los 293 días Génesis-legibles (2024–2030) con los 30 eclipses del mismo periodo (astronomy-engine: eclipses solares globales + lunares). Días Génesis con eclipse en ±10 días: <strong>6,5 %</strong> (19/293). Esperanza aleatoria (eclipses/año × ventana 21 d / 365): <strong>24,7 %</strong>. Los días Génesis <strong>evitan</strong> las ventanas eclipsales; el motor es la posición de los planetas lentos, no la geometría Sol–Luna–nodo.</p>',
    '<p>The 293 Genesis-legible days (2024–2030) were contrasted with the 30 eclipses of the same period (astronomy-engine: global solar + lunar eclipses). Genesis days with an eclipse within ±10 days: <strong>6.5 %</strong> (19/293). Random expectation (eclipses/year × 21-day window / 365): <strong>24.7 %</strong>. Genesis days <strong>avoid</strong> eclipse windows; the engine is the position of the slow planets, not the Sun–Moon–node geometry.</p>')
rep('<h3 id="9-4-37-y-73-en-el-año-solar-la-relación-celeste-real">9.4 37 y 73 en el año solar (la relación celeste real)</h3>', '<h3 id="9-4-37-y-73-en-el-año-solar-la-relación-celeste-real">9.4 37 and 73 in the solar year (the real celestial relation)</h3>')
rep('<p>Aunque 37 y 73 no rigen los eclipses (§9.2–9.3), <strong>sí encajan de forma exacta en el año solar civil</strong>, y ese encaje es la conexión celeste genuina de los factores de Génesis 1:1:</p>',
    '<p>Although 37 and 73 do not govern eclipses (§9.2–9.3), <strong>they do fit exactly into the civil solar year</strong>, and that fit is the genuine celestial connection of the factors of Genesis 1:1:</p>')
rep('<ol><li><strong>365 = 73 × 5.</strong> El año solar entero (civil, juliano/egipcio) se factoriza como 73 pentadas de 5 días.</li><li><strong>2701 × 5 = 13 505 = 37 × 365.</strong> La gematría de Génesis 1:1 expresada en pentadas equivale a <strong>37 años civiles exactos</strong>.</li><li><strong>Cierre coherente:</strong> 2701 = 37 × 73, y 2701 pentadas = 37 años × 73 pentadas/año. Es decir, <em>Génesis 1:1</em> = (37 años) × (73 pentadas/año).</li></ol>',
    '<ol><li><strong>365 = 73 × 5.</strong> The whole (civil, Julian/Egyptian) solar year factors as 73 pentads of 5 days.</li><li><strong>2701 × 5 = 13 505 = 37 × 365.</strong> The gematria of Genesis 1:1 expressed in pentads equals <strong>exactly 37 civil years</strong>.</li><li><strong>Coherent closure:</strong> 2701 = 37 × 73, and 2701 pentads = 37 years × 73 pentads/year. That is, <em>Genesis 1:1</em> = (37 years) × (73 pentads/year).</li></ol>')
rep('<p>Esta es una <strong>identidad aritmética sólida</strong> del año solar de 365 días. Hay que acotarla con precisión:</p>',
    '<p>This is a <strong>solid arithmetic identity</strong> of the 365-day solar year. It must be precisely bounded:</p>')
rep('<ul><li>Usa el <strong>año civil de 365 d</strong>, no el año trópico (365,2422 d): 13 505 / 365,2422 = 36,975 años (≈ 37, pero no exacto). Es, pues, aritmética <strong>calendárica civil</strong>, no mecánica orbital.</li><li><strong>No corresponde a un calendario antiguo atestiguado.</strong> El calendario de Enoc/Qumrán es de <strong>364 d = 52 semanas = 4×91</strong> (no divisible en pentadas: 364/5 = 72,8); el egipcio civil es <strong>365 = 36 decanos×10 + 5 epagómenos</strong> (los 5 días son un bloque aparte, no una 73.ª pentada). Ninguno organiza el año en 73 pentadas. La estructura 73×5 es una factorización del entero 365, no una práctica calendárica documentada.</li><li><strong>37 lunaciones ≈ 3 años solares</strong> es solo aproximado: 37×29,5306 = 1092,63 d vs 3×365,2422 = 1095,73 d (Δ 3,1 d); 37 no es un ciclo lunisolar clásico (lo son 19, 8, 76).</li></ul>',
    '<ul><li>It uses the <strong>civil year of 365 d</strong>, not the tropical year (365.2422 d): 13 505 / 365.2422 = 36.975 years (≈ 37, but not exact). It is, then, <strong>civil-calendar</strong> arithmetic, not orbital mechanics.</li><li><strong>It does not correspond to an attested ancient calendar.</strong> The Enoch/Qumran calendar is <strong>364 d = 52 weeks = 4×91</strong> (not divisible into pentads: 364/5 = 72.8); the Egyptian civil is <strong>365 = 36 decans×10 + 5 epagomenal days</strong> (the 5 days are a separate block, not a 73rd pentad). Neither organizes the year into 73 pentads. The 73×5 structure is a factorization of the integer 365, not a documented calendrical practice.</li><li><strong>37 lunations ≈ 3 solar years</strong> is only approximate: 37×29.5306 = 1092.63 d vs 3×365.2422 = 1095.73 d (Δ 3.1 d); 37 is not a classic lunisolar cycle (those are 19, 8, 76).</li></ul>')
rep('<blockquote><strong>Síntesis.</strong> 37 y 73 no son números de eclipse (§9.2–9.3), pero <strong>sí son números del año solar civil</strong>: 73 pentadas = 365 d, y 2701 pentadas = 37 años. La gematría de Génesis 1:1 (37×73) se refleja así en la medida del año: 37 años × 73 pentadas. Es coherencia aritmética del calendario civil, no de la mecánica eclipsal.</blockquote>',
    '<blockquote><strong>Synthesis.</strong> 37 and 73 are not eclipse numbers (§9.2–9.3), but <strong>they are numbers of the civil solar year</strong>: 73 pentads = 365 d, and 2701 pentads = 37 years. The gematria of Genesis 1:1 (37×73) is thus reflected in the measure of the year: 37 years × 73 pentads. It is arithmetic coherence of the civil calendar, not of eclipse mechanics.</blockquote>')
rep('<h3 id="9-5-preservación-textual-masorética">9.5 Preservación textual masorética</h3>', '<h3 id="9-5-preservación-textual-masorética">9.5 Masoretic textual preservation</h3>')
rep('<p>La estructura 37×73 = 2701 de Génesis 1:1 adquiere relevancia en el contexto de la <strong>preservación textual masorética</strong> (ss. VI–X d.C.): los masoretas desarrollaron un sistema de recuento para impedir alteraciones de la Torá —número exacto de letras, palabras y versos de cada libro; letra central y palabra central marcadas (la palabra central de la Torá es דָּרֹשׁ דָּרַשׁ, <em>darosh darash</em>, Levítico 10:16)—. En ese marco, una factorización tan cargada del primer verso (2701 = 37×73, 73.º triangular, 2701+1072 = 3773) funciona como un <strong>sello verificable</strong>: cualquier cambio de letras alteraría la suma y, con ella, la factorización. Nótese, no obstante, que el test de §13 muestra que el espejo-palíndromo 2701→3773 <strong>no es selectivo</strong> (lo cumple ~38 % de cualquier verso), de modo que el sello operativo es la <strong>factorización 37×73 específica de 2701</strong>, no el espejo generalizado.</p>',
    '<p>The 37×73 = 2701 structure of Genesis 1:1 gains relevance in the context of <strong>Masoretic textual preservation</strong> (6th–10th c. CE): the Masoretes developed a counting system to prevent alterations to the Torah —exact number of letters, words, and verses of each book; central letter and central word marked (the central word of the Torah is דָּרֹשׁ דָּרַשׁ, <em>darosh darash</em>, Leviticus 10:16)—. In that framework, so loaded a factorization of the first verse (2701 = 37×73, 73rd triangular, 2701+1072 = 3773) functions as a <strong>verifiable seal</strong>: any change of letters would alter the sum and, with it, the factorization. Note, however, that the test of §13 shows that the mirror-palindrome 2701→3773 <strong>is not selective</strong> (~38 % of any verse fulfills it), so the operative seal is the <strong>specific 37×73 factorization of 2701</strong>, not the generalized mirror.</p>')

# ---- section 10 ----
rep('<h2 id="10-regla-de-lectura-formalización">10. Regla de lectura (formalización)</h2>', '<h2 id="10-regla-de-lectura-formalización">10. Reading rule (formalization)</h2>')
rep('<p>Sea <em>O(t)</em> ⊆ {ה,ו,ז,ח,ט,י,ל,נ,ס,ע,צ,ק} el conjunto de letras simples cuyo signo está ocupado por <strong>al menos uno</strong> de los 10 cuerpos (Sol, Luna, Mercurio, Venus, Marte, Júpiter, Saturno, Urano, Neptuno, Plutón) en el instante <em>t</em>. Sea <em>S(w)</em> el conjunto de letras simples de la palabra <em>w</em> (tras normalización de finales a regulares).</p>',
    '<p>Let <em>O(t)</em> ⊆ {ה,ו,ז,ח,ט,י,ל,נ,ס,ע,צ,ק} be the set of simple letters whose sign is occupied by <strong>at least one</strong> of the 10 bodies (Sun, Moon, Mercury, Venus, Mars, Jupiter, Saturn, Uranus, Neptune, Pluto) at instant <em>t</em>. Let <em>S(w)</em> be the set of simple letters of word <em>w</em> (after normalizing finals to regulars).</p>')
rep('<blockquote><strong>Definición (legibilidad).</strong> <em>w</em> es legible en <em>t</em> ⟺ <em>S(w)</em> ⊆ <em>O(t)</em>.</blockquote>',
    '<blockquote><strong>Definition (legibility).</strong> <em>w</em> is legible at <em>t</em> ⟺ <em>S(w)</em> ⊆ <em>O(t)</em>.</blockquote>')
rep('<p><strong>Regla de reutilización.</strong> Madres y dobles siempre disponibles y reutilizables. Una simple se lee si su signo está ocupado; <strong>repetir una simple no requiere conjunción</strong> (pertenencia, no consumo). Las palabras sin simples (ברא «creó», אב «padre», שבת «sábado», אמת «verdad») son legibles siempre.</p>',
    '<p><strong>Reuse rule.</strong> Mothers and doubles are always available and reusable. A simple is read if its sign is occupied; <strong>repeating a simple does not require conjunction</strong> (membership, not consumption). Words without simples (ברא "created", אב "father", שבת "sabbath", אמת "truth") are always legible.</p>')
rep('<p>Validación (<code>tests.mjs</code>, 44 aserciones en verde): 12 ocupados → 6045 palabras legibles; solo Virgo → 634; 0 signos → 377 siempre legibles.</p>',
    '<p>Validation (<code>tests.mjs</code>, 44 green assertions): 12 occupied → 6045 legible words; only Virgo → 634; 0 signs → 377 always legible.</p>')
rep('<p><strong>El descarte es medible y masivo.</strong> Para Génesis 1:1, sobre 2024–2030 (2555 días), solo <strong>293 días (11,5 %)</strong> son legibles → la regla posicional <strong>descarta el 88,5 %</strong> de las fechas. Para יהוה, legible la mayor parte del año (cadencia ~mensual). El descarte no es aritmético (palíndromo, §13.2) sino <strong>posicional</strong>: lo que distingue una lectura válida de una inválida es qué signos están ocupados, no la suma de sus letras.</p>',
    '<p><strong>The discard is measurable and massive.</strong> For Genesis 1:1, over 2024–2030 (2555 days), only <strong>293 days (11.5 %)</strong> are legible → the positional rule <strong>discards 88.5 %</strong> of dates. For יהוה, legible most of the year (~monthly cadence). The discard is not arithmetic (palindrome, §13.2) but <strong>positional</strong>: what distinguishes a valid reading from an invalid one is which signs are occupied, not the sum of its letters.</p>')

# ---- section 11 (figcaption + prose; SVG labels handled globally in tr_en5) ----
rep('<figcaption><span class="fnum">Fig. 4.</span> Cadencia de יהוה. La línea dorada traza el camino י→ה→ו→ה sobre los signos Virgo-Aries-Tauro-Aries, ocupados por planetas rápidos (2026-02-03, יהוה legible). Sin Acuario (צ) en el conjunto → no es Génesis: la cadencia es mensual, no secular.</figcaption>',
    '<figcaption><span class="fnum">Fig. 4.</span> Cadence of יהוה. The golden line traces the path י→ה→ו→ה over the signs Virgo-Aries-Taurus-Aries, occupied by fast planets (2026-02-03, יהוה legible). Without Aquarius (צ) in the set → it is not Genesis: the cadence is monthly, not secular.</figcaption>')
rep('<text x="220" y="226" text-anchor="middle" font-family="sans-serif" font-size="9" fill="#8aa0c0">יהוה: {י Virgo, ה Aries, ו Tauro} — cadencia ~mensual (sin Acuario: no es Génesis)</text>',
    '<text x="220" y="226" text-anchor="middle" font-family="sans-serif" font-size="9" fill="#8aa0c0">יהוה: {י Virgo, ה Aries, ו Taurus} — cadence ~monthly (without Aquarius: not Genesis)</text>')
rep('<p><em>S</em>(יהוה) = {י,ה,ו} = Virgo + Aries + Tauro. La Luna recorre los 12 signos cada 27,3 días, de modo que esos tres signos están ocupados la mayor parte del año, con breves vacíos → cadencia <strong>~mensual</strong>. יהוה <strong>no</strong> marca eras: marca el mes. Sus tres signos son rellenados por planetas rápidos.</p>',
    '<p><em>S</em>(יהוה) = {י,ה,ו} = Virgo + Aries + Taurus. The Moon traverses the 12 signs every 27.3 days, so those three signs are occupied most of the year, with brief voids → <strong>~monthly</strong> cadence. יהוה does <strong>not</strong> mark eras: it marks the month. Its three signs are filled by fast planets.</p>')
rep('<p>Relación con el tetramorfo (§6): las dos Heh de יהוה son <strong>Aries (טלה, carnero)</strong> y la Vav es <strong>Tauro (שור, buey)</strong>; la Yod es <strong>Virgo (בתולה)</strong>. El Nombre se compone, pues, de carnero + buey + virgen.</p>',
    '<p>Relation to the tetramorph (§6): the two Heh of יהוה are <strong>Aries (טלה, ram)</strong> and the Vav is <strong>Taurus (שור, ox)</strong>; the Yod is <strong>Virgo (בתולה)</strong>. The Name is thus composed of ram + ox + virgin.</p>')

# ---- section 12 ----
rep('<figcaption><span class="fnum">Fig. 5.</span> Génesis 1:1 legible (2026-09-01, ventana 2025–2038). El conjunto {י,ה,ל,ו,צ} = Virgo+Aries+Libra+Tauro+Acuario exige Acuario (צ, anclado por Plutón) y Aries (ה, anclado por Neptuno): el par lento Neptuno–Plutón en fase Aries–Acuario abre la ventana de ~13 años que recurre cada ~491 años.</figcaption>',
    '<figcaption><span class="fnum">Fig. 5.</span> Genesis 1:1 legible (2026-09-01, window 2025–2038). The set {י,ה,ל,ו,צ} = Virgo+Aries+Libra+Taurus+Aquarius demands Aquarius (צ, anchored by Pluto) and Aries (ה, anchored by Neptune): the slow Neptune–Pluto pair in Aries–Aquarius phase opens the ~13-year window that recurs every ~491 years.</figcaption>')
rep('<text x="220" y="226" text-anchor="middle" font-family="sans-serif" font-size="9" fill="#8aa0c0">Génesis 1:1 legible — ventana 2025–2038 (Neptuno∈Aries, Plutón∈Acuario)</text>',
    '<text x="220" y="226" text-anchor="middle" font-family="sans-serif" font-size="9" fill="#8aa0c0">Genesis 1:1 legible — window 2025–2038 (Neptune∈Aries, Pluto∈Aquarius)</text>')
rep('<p><em>S</em>(Génesis 1:1) = {י,ה,ל,ו,צ} = Virgo + Aries + Libra + Tauro + <strong>Acuario</strong>. Virgo, Libra y Tauro los rellenan los planetas rápidos en meses; pero <strong>Aries y Acuario</strong> solo son anclados de forma persistente por los dos planetas más lentos: <strong>Neptuno (Aries) y Plutón (Acuario)</strong>. La legibilidad sostenida exige <strong>Plutón ∈ Acuario ∧ Neptuno ∈ Aries</strong>.</p>',
    '<p><em>S</em>(Genesis 1:1) = {י,ה,ל,ו,צ} = Virgo + Aries + Libra + Taurus + <strong>Aquarius</strong>. Virgo, Libra, and Taurus are filled by fast planets in months; but <strong>Aries and Aquarius</strong> are anchored persistently only by the two slowest planets: <strong>Neptune (Aries) and Pluto (Aquarius)</strong>. Sustained legibility demands <strong>Pluto ∈ Aquarius ∧ Neptune ∈ Aries</strong>.</p>')
rep('<p>Escaneo (−600 a.C. a 2400 d.C., paso trimestral, fechas históricas vía <code>setUTCFullYear</code>):</p>',
    '<p>Scan (−600 BCE to 2400 CE, quarterly step, historical dates via <code>setUTCFullYear</code>):</p>')
rep('<th>#</th><th>ventana</th><th>duración</th><th>separación</th><th>correlato religioso-lingüístico</th>', '<th>#</th><th>window</th><th>duration</th><th>separation</th><th>religious-linguistic correlate</th>')
rep('<td><strong>−427 a −417 a.C.</strong></td>', '<td><strong>−427 to −417 BCE</strong></td>')
rep('<td><strong>61–73 d.C.</strong></td>', '<td><strong>61–73 CE</strong></td>')
rep('<td><strong>552–565 d.C.</strong></td>', '<td><strong>552–565 CE</strong></td>')
rep('<td><strong>1043–1056 d.C.</strong></td>', '<td><strong>1043–1056 CE</strong></td>')
rep('<td><strong>1535–1547 d.C.</strong></td>', '<td><strong>1535–1547 CE</strong></td>')
rep('<td><strong>2025–2038 d.C.</strong></td>', '<td><strong>2025–2038 CE</strong></td>')
rep('<td>~10 a</td>', '<td>~10 y</td>')
rep('<td>~13 a</td>', '<td>~13 y</td>')
rep('<td>~12 a</td>', '<td>~12 y</td>')
rep('<td>488 a</td>', '<td>488 y</td>')
rep('<td>491 a</td>', '<td>491 y</td>')
rep('<td>492 a</td>', '<td>492 y</td>')
rep('<td>490 a</td>', '<td>490 y</td>')
rep('<td><strong>Edad Axial</strong>: Platón (n. 427), redacción final de la Torá, Buda</td>', '<td><strong>Axial Age</strong>: Plato (b. 427), final redaction of the Torah, Buddha</td>')
rep('<td><strong>Destrucción del Segundo Templo (70)</strong>: judaísmo rabínico, ruptura cristiana</td>', '<td><strong>Destruction of the Second Temple (70)</strong>: rabbinic Judaism, Christian split</td>')
rep('<td>Justiniano, Santa Sofía, cierre del Talmud, víspera del Islam</td>', '<td>Justinian, Hagia Sophia, closing of the Talmud, eve of Islam</td>')
rep('<td><strong>Cisma de Oriente/Occidente (1054)</strong></td>', '<td><strong>East/West Schism (1054)</strong></td>')
rep('<td><strong>Reforma</strong> (1517), <strong>Copérnico</strong>, <em>De revolutionibus</em> (1543)</td>', '<td><strong>Reformation</strong> (1517), <strong>Copernicus</strong>, <em>De revolutionibus</em> (1543)</td>')
rep('<td>ventana actual</td>', '<td>current window</td>')
rep('<p>Separación media <strong>490,5 años</strong> = ciclo sinódico Neptuno–Plutón (492,3 a). 2024–2030 arroja <strong>293 días</strong> Génesis-legibles, clúster denso 2028–2029 (primero: 2026-09-01).</p>',
    '<p>Mean separation <strong>490.5 years</strong> = Neptune–Pluto synodic cycle (492.3 y). 2024–2030 yields <strong>293 days</strong> Genesis-legible, dense cluster 2028–2029 (first: 2026-09-01).</p>')
rep('<blockquote>Génesis 1:1 es un <strong>verso-marca-de-era</strong>: su conjunto de simples es exactamente el conjunto de signos que activa la configuración sinódica Neptuno–Plutón en fase Aries–Acuario. La diferencia estructural con יהוה (Acuario ∈ <em>S</em>) es lo que separa la cadencia mensual de la secular. La <strong>Era de Acuario</strong> precesional (~2441 d.C., §3) y la ventana sinódica (~491 a) coinciden ahora.</blockquote>',
    '<blockquote>Genesis 1:1 is an <strong>era-marker-verse</strong>: its set of simples is exactly the set of signs activated by the Neptune–Pluto synodic configuration in Aries–Aquarius phase. The structural difference with יהוה (Aquarius ∈ <em>S</em>) is what separates the monthly cadence from the secular one. The precessional <strong>Age of Aquarius</strong> (~2441 CE, §3) and the synodic window (~491 y) coincide now.</blockquote>')

# ---- section 13 ----
rep('<h2 id="13-resultado-iii-2701-el-espejo-palíndromo-y-los-modelos-nul">13. Resultado III — 2701, el espejo-palíndromo y los modelos nulos</h2>', '<h2 id="13-resultado-iii-2701-el-espejo-palíndromo-y-los-modelos-nul">13. Result III — 2701, the mirror-palindrome, and the null models</h2>')
rep('<p>Propiedades de Génesis 1:1: 2701 = 37×73; 73.º triangular; 2701 + 1072 = 3773 (palíndromo).</p>',
    '<p>Properties of Genesis 1:1: 2701 = 37×73; 73rd triangular; 2701 + 1072 = 3773 (palindrome).</p>')
rep('<p><strong>Test de selectividad.</strong> ¿Distingue el espejo a Génesis de texto arbitrario? Se generaron 30 660 versos nulos (20× Génesis, n = 1533), con (a) Markov orden-1 sobre letras del propio Génesis y (b) iid uniforme, ambas con la <strong>distribución de longitudes</strong> real. PRNG determinista (mulberry32, semilla 20260807) para reproducibilidad exacta:</p>',
    '<p><strong>Selectivity test.</strong> Does the mirror distinguish Genesis from arbitrary text? 30 660 null verses were generated (20× Genesis, n = 1533), with (a) order-1 Markov over the letters of Genesis itself and (b) iid uniform, both with the real <strong>length distribution</strong>. Deterministic PRNG (mulberry32, seed 20260807) for exact reproducibility:</p>')
rep('<th>propiedad</th><th>Génesis (n=1533)</th><th>Markov ord-1</th><th>uniforme iid</th>', '<th>property</th><th>Genesis (n=1533)</th><th>Markov ord-1</th><th>uniform iid</th>')
rep('<td>G + rev(G) = palíndromo</td><td><strong>39,3 %</strong> (603)</td><td>38,8 % (11 883)</td><td>38,0 % (11 657)</td>', '<td>G + rev(G) = palindrome</td><td><strong>39.3 %</strong> (603)</td><td>38.8 % (11 883)</td><td>38.0 % (11 657)</td>')
rep('<td>G divisible por 37</td><td>3,13 % (48)</td><td>2,80 % (858)</td><td>2,79 % (855)</td>', '<td>G divisible by 37</td><td>3.13 % (48)</td><td>2.80 % (858)</td><td>2.79 % (855)</td>')
rep('<td>G triangular</td><td>1,57 % (24)</td><td>1,20 % (368)</td><td>1,15 % (352)</td>', '<td>G triangular</td><td>1.57 % (24)</td><td>1.20 % (368)</td><td>1.15 % (352)</td>')
rep('<p>Ratio espejo Génesis/Markov = <strong>1,01×</strong>; Génesis/uniforme = 1,03×. <strong>No discrimina</strong>: ~4 de cada 10 versos hebreos arbitrarios de longitud comparable ya lo cumplen, por la aritmética de la suma con inversión de cifras. La divisibilidad por 37 muestra un exceso débil (~1,12×) y la triangularidad un exceso moderado (~1,31×); con n = 1533 ninguno es concluyente, y ambos son independientes del espejo.</p>',
    '<p>Mirror ratio Genesis/Markov = <strong>1.01×</strong>; Genesis/uniform = 1.03×. <strong>It does not discriminate</strong>: ~4 of every 10 arbitrary Hebrew verses of comparable length already fulfill it, by the arithmetic of digit-reversal sum. Divisibility by 37 shows a weak excess (~1.12×) and triangularity a moderate excess (~1.31×); with n = 1533 neither is conclusive, and both are independent of the mirror.</p>')
rep('<h3 id="13-1-nulo-a-nivel-palabra-es-el-palíndromo-espejo-un-checksu">13.1 Nulo a nivel palabra (¿es el palíndromo-espejo un checksum?)</h3>', '<h3 id="13-1-nulo-a-nivel-palabra-es-el-palíndromo-espejo-un-checksu">13.1 Word-level null (is the mirror-palindrome a checksum?)</h3>')
rep('<p>La hipótesis del «checksum por palíndromo» (§6.2, §9.5) exige que el palíndromo-espejo sea <strong>raro</strong>. No lo es. Test directo sobre el lexicón Strong (6045 raíces) y los 12 <em>mazzalot</em> (<code>calc_mazzalot.mjs</code>):</p>',
    '<p>The "checksum by palindrome" hypothesis (§6.2, §9.5) requires the mirror-palindrome to be <strong>rare</strong>. It is not. Direct test over the Strong lexicon (6045 roots) and the 12 <em>mazzalot</em> (<code>calc_mazzalot.mjs</code>):</p>')
rep('<th>conjunto</th><th>palíndromo-espejo</th><th>tasa</th>', '<th>set</th><th>mirror-palindrome</th><th>rate</th>')
rep('<td>lexicón Strong (6045 raíces)</td><td>2895</td><td><strong>47,9 %</strong></td>', '<td>Strong lexicon (6045 roots)</td><td>2895</td><td><strong>47.9 %</strong></td>')
rep('<td>Génesis (versos, n=1533)</td><td>603</td><td>39,3 %</td>', '<td>Genesis (verses, n=1533)</td><td>603</td><td>39.3 %</td>')
rep('<p>Por número de cifras de la gematría: 1 cifra 5,1 %, 2 cifras 54,6 %, 3 cifras 45,8 %, 4 cifras 84,7 %. La tasa crece con la longitud porque más pares de cifras pueden sumar ≤ 9 sin acarreo.</p>',
    '<p>By number of digits of the gematria: 1 digit 5.1 %, 2 digits 54.6 %, 3 digits 45.8 %, 4 digits 84.7 %. The rate grows with length because more digit pairs can sum ≤ 9 without carry.</p>')
rep('<p><strong>Implicación:</strong> ~1 de cada 2 palabras hebreas cualesquiera son palíndromo-espejo. Que <em>Egel</em>→404, <em>Ayil</em>→55, <em>Shor</em>→1111 lo sean no es, por sí solo, evidencia de diseño: es lo esperable por la aritmética decimal. El espejo <strong>no puede funcionar como checksum</strong> porque no discrimina texto «marcado» de texto arbitrario. Lo que sí es específico de esas palabras son las <strong>sumas con valor astronómico</strong> (Egel+Ayil = 144; Shor = 2×suma(1..22)) —aritmética real, pero cuya atribución a intención autoral requiere un nulo de «números con significado» que no se define aquí (problema de comparaciones múltiples).</p>',
    '<p><strong>Implication:</strong> ~1 of every 2 arbitrary Hebrew words is a mirror-palindrome. That <em>Egel</em>→404, <em>Ayil</em>→55, <em>Shor</em>→1111 are so is not, by itself, evidence of design: it is what is expected from decimal arithmetic. The mirror <strong>cannot function as a checksum</strong> because it does not discriminate "marked" text from arbitrary text. What is specific to those words are the <strong>sums with astronomical value</strong> (Egel+Ayil = 144; Shor = 2×sum(1..22)) —real arithmetic, but whose attribution to authorial intention requires a null of "numbers with meaning" that is not defined here (multiple-comparisons problem).</p>')
rep('<h3 id="13-2-nivel-frase-y-el-palíndromo-como-criterio-de-validez">13.2 Nivel frase y el palíndromo como criterio de validez</h3>', '<h3 id="13-2-nivel-frase-y-el-palíndromo-como-criterio-de-validez">13.2 Phrase level and the palindrome as a validity criterion</h3>')
rep('<p>Dos objeciones metodológicas exigen ir más allá del nivel palabra: (i) las unidades reales del texto son <strong>frases, verbos y números grandes</strong>, no palabras aisladas; (ii) la hipótesis de que el palíndromo-espejo es <strong>el método para distinguir qué lecturas del cielo son válidas y cuáles no</strong> (descartando miles de combinaciones), no un <em>checksum</em>.</p>',
    '<p>Two methodological objections require going beyond the word level: (i) the real units of the text are <strong>phrases, verses, and large numbers</strong>, not isolated words; (ii) the hypothesis that the mirror-palindrome is <strong>the method to distinguish which readings of the sky are valid and which are not</strong> (discarding thousands of combinations), not a <em>checksum</em>.</p>')
rep('<p><strong>(i) Nivel frase.</strong> Computado sobre los 1533 versos de Génesis (<code>calc_phrase.mjs</code>), desglosado por cifras de la gematría del verso:</p>',
    '<p><strong>(i) Phrase level.</strong> Computed over the 1533 verses of Genesis (<code>calc_phrase.mjs</code>), broken down by digits of the verse gematria:</p>')
rep('<th>nivel</th><th>unidad</th><th>palíndromo-espejo</th>', '<th>level</th><th>unit</th><th>mirror-palindrome</th>')
rep('<td>palabra</td><td>6045 raíces (lexicón)</td><td>47,9 %</td>', '<td>word</td><td>6045 roots (lexicon)</td><td>47.9 %</td>')
rep('<td><strong>frase</strong></td><td>versos de Génesis (n=1533)</td><td><strong>39,3 %</strong></td>', '<td><strong>phrase</strong></td><td>verses of Genesis (n=1533)</td><td><strong>39.3 %</strong></td>')
rep('<td>frase grande</td><td>versos con gematría ≥ 1000 (n=1503)</td><td>39,6 %</td>', '<td>large phrase</td><td>verses with gematria ≥ 1000 (n=1503)</td><td>39.6 %</td>')
rep('<p>La frase es <strong>más selectiva</strong> que la palabra (39,3 % vs 47,9 %): la objeción es correcta en la dirección. Pero la rarefacción se detiene ahí —los versos largos (gematría ≥ 1000, ya 4 cifras) no palindroman menos que el total (39,6 % vs 39,3 %)—, y la tasa sigue siendo indistinguible del nulo de Markov (38,8 %, §13). La magnitud del número, por sí sola, no vuelve raro al espejo.</p>',
    '<p>The phrase is <strong>more selective</strong> than the word (39.3 % vs 47.9 %): the objection is correct in direction. But the rarefaction stops there —long verses (gematria ≥ 1000, already 4 digits) do not palindrome less than the total (39.6 % vs 39.3 %)—, and the rate remains indistinguishable from the Markov null (38.8 %, §13). The magnitude of the number, by itself, does not make the mirror rare.</p>')
rep('<p><strong>(ii) El palíndromo como selector de lecturas.</strong> Test directo: la «frase del cielo» en una fecha = las letras simples de los 10 cuerpos ordenadas; su gematría + espejo. Comparando días Génesis-legibles (válidos) vs no-legibles (inválidos) sobre 2024–2030:</p>',
    '<p><strong>(ii) The palindrome as a selector of readings.</strong> Direct test: the "phrase of the sky" at a date = the simple letters of the 10 bodies, ordered; its gematria + mirror. Comparing Genesis-legible (valid) vs non-legible (invalid) days over 2024–2030:</p>')
rep('<th>clase de día</th><th>palíndromo-espejo</th>', '<th>day class</th><th>mirror-palindrome</th>')
rep('<td>Génesis-legible (n=293)</td><td><strong>30,7 %</strong></td>', '<td>Genesis-legible (n=293)</td><td><strong>30.7 %</strong></td>')
rep('<td>Génesis-no-legible (n=2262)</td><td><strong>32,4 %</strong></td>', '<td>Genesis-non-legible (n=2262)</td><td><strong>32.4 %</strong></td>')
rep('<p>Si el palíndromo fuera el criterio de validez, los legibles palindromarían <em>más</em>. Palindroman <em>menos</em> (30,7 % < 32,4 %). <strong>El palíndromo no selecciona las lecturas válidas.</strong> Lo que sí las selecciona —y descarta el 88,5 % de las fechas (§10)— es la regla <strong>posicional</strong> <em>S</em> ⊆ <em>O</em>. El espejo y la pertenencia a conjunto son criterios independientes; el segundo opera, el primero no separa.</p>',
    '<p>If the palindrome were the validity criterion, the legible ones would palindrome <em>more</em>. They palindrome <em>less</em> (30.7 % < 32.4 %). <strong>The palindrome does not select the valid readings.</strong> What does select them —and discards 88.5 % of dates (§10)— is the <strong>positional</strong> rule <em>S</em> ⊆ <em>O</em>. The mirror and set membership are independent criteria; the second operates, the first does not separate.</p>')
rep('<blockquote><strong>Síntesis.</strong> El palíndromo-espejo es real en casos concretos (2701→3773, Egel→404) y la frase es más selectiva que la palabra (39 % vs 48 %), pero no alcanza para ser ni <em>checksum</em> ni <em>criterio de validez de lectura</em>: no distingue de un nulo de Markov, no rareface con la magnitud, y no separa días legibles de inválidos. El descarte operacional del <em>Lector del Cielo</em> es <strong>posicional</strong> (<em>S</em> ⊆ <em>O</em>), no aritmético. Lo que sí es atestado y, para los 72 versos, demostrado, es la <strong>ingeniería intencional de letras</strong> como práctica (§6.3) —un hecho histórico, distinto de la selectividad estadística del espejo.</blockquote>',
    '<blockquote><strong>Synthesis.</strong> The mirror-palindrome is real in specific cases (2701→3773, Egel→404) and the phrase is more selective than the word (39 % vs 48 %), but it does not suffice to be either a <em>checksum</em> or a <em>criterion of reading validity</em>: it does not distinguish from a Markov null, it does not rarefy with magnitude, and it does not separate legible from invalid days. The operational discard of the <em>Reader of the Sky</em> is <strong>positional</strong> (<em>S</em> ⊆ <em>O</em>), not arithmetic. What is attested and, for the 72 verses, demonstrated, is the <strong>intentional letter engineering</strong> as a practice (§6.3) —a historical fact, distinct from the statistical selectivity of the mirror.</blockquote>')

missing=[]
for a,b in R:
    if a in src: src = src.replace(a,b)
    else: missing.append(a[:70])
io.open('../pdf/lector-del-cielo_EN.html','w',encoding='utf-8').write(src)
print("part4 done; reps:",len(R),"missing:",len(missing))
for m in missing: print("  MISS:",m)