#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import io, re
src = io.open('../pdf/lector-del-cielo_EN.html', encoding='utf-8').read()
R = []
def rep(a,b): R.append((a,b))

# ---- section 14 ----
rep('<h2 id="14-resultado-iv-el-144">14. Resultado IV — El 144</h2>', '<h2 id="14-resultado-iv-el-144">14. Result IV — The 144</h2>')
rep('<ol><li><strong>144 = 12²</strong> — las 12 simples al cuadrado; el cuadrado de la completud del zodiaco.</li><li><strong>144 = meses lunares de los 12 años comunes del ciclo metónico:</strong> 12×12 + 7×13 = 144 + 91 = 235 (§7). El 144 es estructural en la sincronía lunar-solar.</li><li><strong>144 = Egel + Ayil = 103 + 41</strong> (§6.2): la gematría del becerro (Era de Tauro que termina) más la del carnero (Era de Aries que comienza) suma 144 —la transición zodiacal en una sola cifra.</li><li><strong>144 000 = 144 × 1000 = 360 × 400.</strong> Aquí 360 = el círculo zodiacal completo (12×30°) y 400 = ת (Tav), la séptima doble, asignada a la <strong>Luna</strong> (§5). 144 000/360 = 400. En el marco del SY, «el círculo entero × la Luna» = 144 000. (Ap 7/14: 144 000 = 12 tribus × 12 000 = 12² × 1000.)</li><li><strong>144 años = 2,01° de precesión</strong> (§3): dos grados del gran reloj precesional.</li><li><strong>144 como divisor de la era y del gran año —solo a la tasa platónica de 72 a/°—:</strong> 144 × 15 = <strong>2160</strong> (era zodiacal a 72 a/°) y 144 × 180 = <strong>25 920</strong> (gran año a 72 a/°). <strong>Caveat:</strong> a la tasa real IAU (50,29″/año) la era es 2147,5 a y el gran año 25 771 a, y <strong>ninguno es divisible por 144</strong> (2147,5/144 = 14,913; 25 771/144 = 178,965). La divisibilidad limpia es propiedad del redondeo 72 a/°, no de la precesión observada.</li></ol>',
    '<ol><li><strong>144 = 12²</strong> — the 12 simples squared; the square of the completeness of the zodiac.</li><li><strong>144 = lunar months of the 12 common years of the Metonic cycle:</strong> 12×12 + 7×13 = 144 + 91 = 235 (§7). 144 is structural in lunar–solar synchrony.</li><li><strong>144 = Egel + Ayil = 103 + 41</strong> (§6.2): the gematria of the calf (ending Era of Taurus) plus that of the ram (beginning Era of Aries) sums to 144 —the zodiacal transition in a single figure.</li><li><strong>144 000 = 144 × 1000 = 360 × 400.</strong> Here 360 = the complete zodiacal circle (12×30°) and 400 = ת (Tav), the seventh double, assigned to the <strong>Moon</strong> (§5). 144 000/360 = 400. In the SY framework, "the whole circle × the Moon" = 144 000. (Rev 7/14: 144 000 = 12 tribes × 12 000 = 12² × 1000.)</li><li><strong>144 years = 2.01° of precession</strong> (§3): two degrees of the great precessional clock.</li><li><strong>144 as a divisor of the era and the great year —only at the Platonic rate of 72 y/°—:</strong> 144 × 15 = <strong>2160</strong> (zodiacal era at 72 y/°) and 144 × 180 = <strong>25 920</strong> (great year at 72 y/°). <strong>Caveat:</strong> at the real IAU rate (50.29″/year) the era is 2147.5 y and the great year 25 771 y, and <strong>neither is divisible by 144</strong> (2147.5/144 = 14.913; 25 771/144 = 178.965). The clean divisibility is a property of the 72 y/° rounding, not of the observed precession.</li></ol>')
rep('<blockquote>El 144 no es una cifra aislada: une el 12 del zodiaco (12²), los 144 meses lunares del Metón, la transición Egel+Ayil, el 144 000 = círculo×Luna (ת) del simbolismo apocalíptico y —a la tasa platónica— la división de la era (2160) y del gran año (25 920). A la tasa observada (50,29″/año) solo retiene el 2,01° por 144 años.</blockquote>',
    '<blockquote>144 is not an isolated figure: it unites the 12 of the zodiac (12²), the 144 lunar months of Meton, the Egel+Ayil transition, the 144 000 = circle×Moon (ת) of apocalyptic symbolism, and —at the Platonic rate— the division of the era (2160) and of the great year (25 920). At the observed rate (50.29″/year) it retains only the 2.01° per 144 years.</blockquote>')

# ---- section 15 ----
rep('<h2 id="15-discusión">15. Discusión</h2>', '<h2 id="15-discusión">15. Discussion</h2>')
rep('<p><strong>Dos ciclos distintos que el sentido común confunde:</strong></p>',
    '<p><strong>Two distinct cycles that common sense confuses:</strong></p>')
rep('<ul><li><strong>~491 años</strong> (sinódico Neptuno–Plutón, fase Aries–Acuario): periodicidad <em>de la ventana de legibilidad de Génesis</em> y, empíricamente, de las re-formaciones religioso-lingüísticas (§12).</li><li><strong>~2148 años</strong> (precesión por signo): periodicidad <em>de la Era zodiacal</em> de fondo (§3). La «intuición de 2000 años» corresponde a esta; pero la <em>legibilidad de Génesis</em> no espera 2000 años entre ventanas, sino ~491.</li></ul>',
    '<ul><li><strong>~491 years</strong> (Neptune–Pluto synodic, Aries–Aquarius phase): periodicity <em>of the Genesis legibility window</em> and, empirically, of the religious-linguistic re-formations (§12).</li><li><strong>~2148 years</strong> (precession per sign): periodicity <em>of the background zodiacal Era</em> (§3). The "2000-year intuition" corresponds to this; but <em>Genesis legibility</em> does not wait 2000 years between windows, but ~491.</li></ul>')
rep('<p><strong>Génesis 1:1 como verso-marca-de-era.</strong> La correlación de las seis ventanas con re-formaciones religioso-lingüísticas (Axial, Templo, Justiniano, Cisma, Reforma, actualidad) es un patrón empírico, no una demostración causal (n = 6). Pero la recurrencia es físicamente explicable (mecánica celeste, no ajuste <em>ad hoc</em>): Génesis 1:1 exige <strong>Acuario</strong> (צ, era entrante) y <strong>Aries</strong> (טלה, era precedente), anclados por los dos planetas más lentos.</p>',
    '<p><strong>Genesis 1:1 as an era-marker-verse.</strong> The correlation of the six windows with religious-linguistic re-formations (Axial, Temple, Justinian, Schism, Reformation, present) is an empirical pattern, not a causal demonstration (n = 6). But the recurrence is physically explicable (celestial mechanics, not an <em>ad hoc</em> fit): Genesis 1:1 demands <strong>Aquarius</strong> (צ, incoming era) and <strong>Aries</strong> (טלה, preceding era), anchored by the two slowest planets.</p>')
rep('<p><strong>Sobre el descarte.</strong> «¿Por qué Génesis y no otra combinación?» — respuesta estructural: el descarte es <strong>posicional</strong> (<em>S</em> ⊆ <em>O</em>). Génesis no se eligió por un sello aritmético (§13 lo descarta, §9.2 descarta 37/73 en eclipses), sino porque <strong>su lista de simples coincide con el conjunto de signos que activa la era</strong>: Acuario (צ) exige a Plutón; Aries (טלה) exige a Neptuno.</p>',
    '<p><strong>On the discard.</strong> "Why Genesis and not another combination?" — structural answer: the discard is <strong>positional</strong> (<em>S</em> ⊆ <em>O</em>). Genesis was not chosen for an arithmetic seal (§13 rules it out, §9.2 rules out 37/73 in eclipses), but because <strong>its list of simples coincides with the set of signs that the era activates</strong>: Aquarius (צ) demands Pluto; Aries (טלה) demands Neptune.</p>')
rep('<p><strong>Sobre el 19.</strong> El 19 une Metón, Saros y la basmala (§8): es el número de la sincronía lunar. El 144 (§14) es el número de la completud del 12 aplicado a la luna (144 meses del Metón) y al círculo (144 000 = 360×400). El 72 es el grado precesional (§3) y el Nombre de 72 letras.</p>',
    '<p><strong>On the 19.</strong> The 19 unites Meton, Saros, and the basmala (§8): it is the number of lunar synchrony. 144 (§14) is the number of the completeness of 12 applied to the moon (144 months of Meton) and to the circle (144 000 = 360×400). 72 is the precessional degree (§3) and the Name of 72 letters.</p>')

# ---- section 16 ----
rep('<h2 id="16-limitaciones">16. Limitaciones</h2>', '<h2 id="16-limitaciones">16. Limitations</h2>')
rep('<ol><li><strong>Mapeo tropical.</strong> Las simples se asignan a sectores tropicales de 30° (§4), no a constelaciones IAU. Decisión de diseño documentada, no corregible sin romper el sistema.</li><li><strong>Efeméride de Plutón.</strong> La precisión degrada fuera de 1700–2200; las ventanas antiguas descansan en determinación a nivel de signo (30°), validada por continuidad suave (variación 19–51°/20a, sin saltos) hasta 600 a.C., no por precisión arcominutosa.</li><li><strong>n = 6.</strong> Las correlaciones históricas son una hipótesis observacional, no una prueba estadística.</li><li><strong>Marco hermético moderno.</strong> La operacionalización del SY como lectura del cielo no es práctica cabalística clásica; es síntesis contemporánea.</li><li><strong>Lexicón.</strong> Strong (OpenScriptures), 6045 raíces consonánticas + 290 glosas españolas curadas; el resto inglés. Incompleto para hebreo post-bíblico.</li><li><strong>37/73 en eclipses.</strong> Resultado <strong>negativo</strong> demostrado (§9.2): no son factores de ningún ciclo eclipsal. Cualquier afirmación de una «relación 37/73-eclipse» carece de base periódica.</li></ol>',
    '<ol><li><strong>Tropical mapping.</strong> The simples are assigned to 30° tropical sectors (§4), not to IAU constellations. A documented design decision, not correctable without breaking the system.</li><li><strong>Pluto ephemeris.</strong> Precision degrades outside 1700–2200; the ancient windows rest on sign-level (30°) determination, validated by smooth continuity (variation 19–51°/20y, no jumps) back to 600 BCE, not by arcminute precision.</li><li><strong>n = 6.</strong> The historical correlations are an observational hypothesis, not a statistical proof.</li><li><strong>Modern hermetic framework.</strong> The operationalization of the SY as a reading of the sky is not classical kabbalistic practice; it is a contemporary synthesis.</li><li><strong>Lexicon.</strong> Strong (OpenScriptures), 6045 consonantal roots + 290 curated Spanish glosses; the rest English. Incomplete for post-biblical Hebrew.</li><li><strong>37/73 in eclipses.</strong> <strong>Negative</strong> result demonstrated (§9.2): they are not factors of any eclipse cycle. Any claim of a "37/73-eclipse relation" lacks a periodic basis.</li></ol>')

# ---- section 17 ----
rep('<h2 id="17-reproducibilidad-y-software">17. Reproducibilidad y software</h2>', '<h2 id="17-reproducibilidad-y-software">17. Reproducibility and software</h2>')
rep('<ul><li><code>index.html</code> + <code>app.bundle.js</code> + <code>lexicon.json</code>: aplicación web (React 18 + astronomy-engine, JSX pre-compilado con esbuild, sin Babel en cliente) que opera todo lo descrito: mapa estelar dinámico, traductor con lexicón completo (cargado por <code>fetch</code>), paneles יהוה / Génesis / Predicción / Eras / Metodología. Servir con <code>python3 -m http.server 8008</code> y abrir <code>http://127.0.0.1:8008/</code>.</li><li><code>cielo-lector.html</code>: versión monolítica legacy (lexicón embebido + Babel-standalone).</li><li><code>tests.mjs</code>: 44 aserciones (astronomía, lector, Génesis, eras, gematría), todas en verde. Monte en jsdom: 11 paneles + SkyMap + traductor, 16/16 en verde.</li><li><code>calc_all.mjs</code>: reproduce los cálculos de §§3–9 y 14 (equinoccios/solsticios, ciclos eclipsales y factorización, sincronía lunar-solar, precesión, eras, 144, tetramorfo, Saros verificado). <code>calc_37_73.mjs</code>: reproduce §9.2–9.4 (factorización 37/73, ciclo nodal ~39 estaciones, pentadas 365=73×5, 2701 pentadas = 37 años civiles). <code>calc_mazzalot.mjs</code>: reproduce §6.2 y §13.1 (Egel/Ayil/Shor, 144×15/180, 253×2, Génesis 1:2=9999, y el nulo de palíndromos a nivel palabra: 47,9 % lexicón, 58 % mazzalot). <code>calc_72.mjs</code>: reproduce §6.3 (231 puertas, AB/BA→ABBA, 3·7·12→231, y verificación en MT de Éxodo 14:19-21 = 72 letras ×3 vía API Sefaria).</li><li><code>palindrome.mjs</code> (Markov/uniforme, §13), <code>calc_phrase.mjs</code> (nulo a nivel frase + test del palíndromo como selector de lecturas, §13.2), <code>slow_scan.mjs</code> (ventanas Neptuno–Plutón, §12), <code>gen_eclipse.mjs</code> (correlación eclipses, §9.3), <code>fetch_gen.mjs</code> (corpus Génesis vía API Sefaria).</li></ul>',
    '<ul><li><code>index.html</code> + <code>app.bundle.js</code> + <code>lexicon.json</code>: web application (React 18 + astronomy-engine, JSX pre-compiled with esbuild, no Babel in the client) that operates everything described: dynamic star map, translator with full lexicon (loaded by <code>fetch</code>), יהוה / Genesis / Prediction / Eras / Methodology panels. Serve with <code>python3 -m http.server 8008</code> and open <code>http://127.0.0.1:8008/</code>.</li><li><code>cielo-lector.html</code>: legacy monolithic version (embedded lexicon + Babel-standalone).</li><li><code>tests.mjs</code>: 44 assertions (astronomy, reader, Genesis, eras, gematria), all green. jsdom mount: 11 panels + SkyMap + translator, 16/16 green.</li><li><code>calc_all.mjs</code>: reproduces the calculations of §§3–9 and 14 (equinoxes/solstices, eclipse cycles and factorization, lunar–solar synchrony, precession, eras, 144, tetramorph, verified Saros). <code>calc_37_73.mjs</code>: reproduces §9.2–9.4 (37/73 factorization, nodal cycle ~39 seasons, pentads 365=73×5, 2701 pentads = 37 civil years). <code>calc_mazzalot.mjs</code>: reproduces §6.2 and §13.1 (Egel/Ayil/Shor, 144×15/180, 253×2, Genesis 1:2=9999, and the word-level palindrome null: 47.9 % lexicon, 58 % mazzalot). <code>calc_72.mjs</code>: reproduces §6.3 (231 gates, AB/BA→ABBA, 3·7·12→231, and MT verification of Exodus 14:19-21 = 72 letters ×3 via the Sefaria API).</li><li><code>palindrome.mjs</code> (Markov/uniform, §13), <code>calc_phrase.mjs</code> (phrase-level null + test of the palindrome as a selector of readings, §13.2), <code>slow_scan.mjs</code> (Neptune–Pluto windows, §12), <code>gen_eclipse.mjs</code> (eclipse correlation, §9.3), <code>fetch_gen.mjs</code> (Genesis corpus via Sefaria API).</li></ul>')

# ---- section 18 ----
rep('<h2 id="18-revisión-crítica-y-asignaturas-pendientes">18. Revisión crítica y asignaturas pendientes</h2>', '<h2 id="18-revisión-crítica-y-asignaturas-pendientes">18. Critical review and outstanding matters</h2>')
rep('<p>Revisión crítica de lo demostrado y de lo que queda fuera:</p>',
    '<p>Critical review of what is demonstrated and of what remains outside:</p>')
rep('<p><strong>Firmemente demostrado (reproducible):</strong></p>',
    '<p><strong>Firmly demonstrated (reproducible):</strong></p>')
rep('<ul><li>Equinoccios/solsticios 2026 con λ☉ = 0/90/180/270° (§4).</li><li>Precesión 50,29″/año → 1°/71,58 a; era 2147,5 a; 144 a = 2,01° (§3).</li><li>Factorización de los 10 ciclos eclipsales; 37/73 <strong>ausentes</strong> (§9.2).</li><li>19 años de eclipse ≈ Saros (Δ 0,46 d); Metón 235 ≈ 19 años (Δ 0,087 d); Saros verificado con dos eclipses reales (§8).</li><li>Metón 12×12+7×13 = 144+91 = 235 (§14); islámico 33 a → drift 358,9 d (§7).</li><li>Tetramorfo a 90° exactos (§6.1); mazzalot = animales (§6).</li><li>Espejo no selectivo (§13): a nivel palabra 47,9 %, a nivel frase 39,3 % (≈ Markov 38,8 %), frases grandes 39,6 %; no separa lecturas válidas de inválidas (30,7 % vs 32,4 %, §13.2). Eclipses no correlacionados (§9.3); 6 ventanas ~491 a (§12).</li></ul>',
    '<ul><li>Equinoxes/solstices 2026 with λ☉ = 0/90/180/270° (§4).</li><li>Precession 50.29″/year → 1°/71.58 y; era 2147.5 y; 144 y = 2.01° (§3).</li><li>Factorization of the 10 eclipse cycles; 37/73 <strong>absent</strong> (§9.2).</li><li>19 eclipse years ≈ Saros (Δ 0.46 d); Meton 235 ≈ 19 years (Δ 0.087 d); Saros verified with two real eclipses (§8).</li><li>Meton 12×12+7×13 = 144+91 = 235 (§14); Islamic 33 y → drift 358.9 d (§7).</li><li>Tetramorph at exact 90° (§6.1); mazzalot = animals (§6).</li><li>Mirror not selective (§13): word level 47.9 %, phrase level 39.3 % (≈ Markov 38.8 %), large phrases 39.6 %; does not separate valid from invalid readings (30.7 % vs 32.4 %, §13.2). Eclipses uncorrelated (§9.3); 6 windows ~491 y (§12).</li></ul>')
rep('<p><strong>Asignaturas pendientes (no cubiertas, y por qué):</strong></p>',
    '<p><strong>Outstanding matters (not covered, and why):</strong></p>')
rep('<ul><li><strong>Saros y series:</strong> el recuento ~73 eclipses/serie se cita como rango estadístico (70–86), no se computó serie por serie. Pendiente: escanear con astronomy-engine una serie saros completa y contar miembros exactos.</li><li><strong>Ayanamsa:</strong> se usa Lahiri (24,18°). Otras ayanamsas (Krishnamurti, Fagan-Bradley, Raman) desplazan las entradas de era en décadas. No se compararon.</li><li><strong>Precesión variable:</strong> 50,29″/año es constante; la precesión real acelera/decelera (modelo IAU 2006 con términos armónicos). Las fechas de era tienen incertidumbre de ~decenas de años por este término, no propagada.</li><li><strong>37/73 — resuelto:</strong> se testó (i) factorización de los 10 ciclos eclipsales (ausentes), (ii) el recuento del ciclo nodal (~39,2 estaciones, no 37), (iii) la relación con el año solar (365 = 73×5; 2701 pentadas = 37 años civiles — §9.4). Queda como extensión testar si 37/73 aparecen en contajes de eclipses por otros cortes (por siglo, por serie). La identidad 2701 = 37×73 es calendárico-civil, no orbital: usa el año de 365 d, no el trópico 365,2422.</li><li><strong>Basmala y código-19:</strong> se reportan los hechos aritméticos (19 letras, 114 = 6×19); no se evalúa la «hipótesis del código 19» de Khalifa (que es una CLAIM estadística discutida, no un hecho astronómico).</li><li><strong>Tetramorfo:</strong> la correspondencia caras↔signos fijos es exegética tradicional (Ezequiel/Apocalipsis); no se «demuestra» astronómicamente, solo se muestra que están a 90°.</li><li><strong>Causalidad de las 6 ventanas:</strong> n = 6; correlación, no prueba causal. Plantear un test estadístico riguroso exigiría una definición operativa de «re-formación religioso-lingüística» y un modelo nulo histórico, fuera del alcance.</li><li><strong>Heptagrama / 7 dobles y los 7 días:</strong> se enuncia (§5, app) pero no se demuestra la cadencia semanal por cálculo.</li><li><strong>Gematría de las 7 palabras y 37:</strong> se da 2701 = 37×73; no se explora la estructura 37×73 como rejilla de las 7 palabras ( Jenkins, <em>Other Bible Code</em>) — citado, no reproducido.</li></ul>',
    '<ul><li><strong>Saros and series:</strong> the ~73 eclipses/series count is cited as a statistical range (70–86), not computed series by series. Pending: scan a complete saros series with astronomy-engine and count exact members.</li><li><strong>Ayanamsa:</strong> Lahiri (24.18°) is used. Other ayanamsas (Krishnamurti, Fagan-Bradley, Raman) shift the era entries by decades. They were not compared.</li><li><strong>Variable precession:</strong> 50.29″/year is constant; real precession accelerates/decelerates (IAU 2006 model with harmonic terms). The era dates carry an uncertainty of ~tens of years from this term, not propagated.</li><li><strong>37/73 — resolved:</strong> (i) factorization of the 10 eclipse cycles (absent), (ii) the nodal cycle count (~39.2 seasons, not 37), (iii) the relation with the solar year (365 = 73×5; 2701 pentads = 37 civil years — §9.4) were tested. It remains as an extension to test whether 37/73 appear in eclipse counts by other cuts (per century, per series). The identity 2701 = 37×73 is calendrical-civil, not orbital: it uses the 365-d year, not the tropical 365.2422.</li><li><strong>Basmala and the 19-code:</strong> the arithmetic facts (19 letters, 114 = 6×19) are reported; Khalifa\'s "19-code hypothesis" is not evaluated (it is a disputed statistical claim, not an astronomical fact).</li><li><strong>Tetramorph:</strong> the faces↔fixed signs correspondence is traditional exegesis (Ezekiel/Revelation); it is not "demonstrated" astronomically, only shown that they are at 90°.</li><li><strong>Causality of the 6 windows:</strong> n = 6; correlation, not causal proof. Positing a rigorous statistical test would require an operational definition of "religious-linguistic re-formation" and a historical null model, beyond scope.</li><li><strong>Heptagram / 7 doubles and the 7 days:</strong> it is stated (§5, app) but the weekly cadence is not demonstrated by calculation.</li><li><strong>Gematria of the 7 words and 37:</strong> 2701 = 37×73 is given; the 37×73 structure as a grid of the 7 words ( Jenkins, <em>Other Bible Code</em>) is not explored — cited, not reproduced.</li></ul>')
rep('<p><strong>Lo que el artículo NO afirma:</strong> no afirma causalidad eclipse-Génesis (negativo, §9.3), no afirma que 37/73 rijan eclipses (negativo, §9.2), no afirma que el espejo seleccione Génesis (negativo, §13, también a nivel palabra 47,9 % y a nivel frase 39,3 %), no afirma que el palíndromo-espejo sea un checksum textual ni el criterio de validez de las lecturas del cielo (falsificado: base alta 48 %, y no separa días legibles de inválidos, 30,7 % vs 32,4 %, §13.1–13.2), no afirma que la gematría tórica codifique astronomía como hecho probado (es hipótesis dentro de una tradición atestada, §6.3), no afirma que el SY clásico sea un oráculo (§1).</p>',
    '<p><strong>What the article does NOT claim:</strong> it does not claim an eclipse-Genesis causality (negative, §9.3), it does not claim that 37/73 govern eclipses (negative, §9.2), it does not claim that the mirror selects Genesis (negative, §13, also word level 47.9 % and phrase level 39.3 %), it does not claim that the mirror-palindrome is a textual checksum or the validity criterion of the readings of the sky (falsified: high 48 % base, and it does not separate legible from invalid days, 30.7 % vs 32.4 %, §13.1–13.2), it does not claim that Toric gematria encodes astronomy as a proven fact (it is a hypothesis within an attested tradition, §6.3), it does not claim that the classical SY is an oracle (§1).</p>')
rep('<p><strong>Lo que el artículo SÍ afirma (con evidencia):</strong> la <strong>ingeniería intencional de letras</strong> es una práctica históricamente atestada (SY, Abulafia, Raziel) y, para los versos de 72 letras de Éxodo 14:19-21, <strong>empíricamente improbable por azar</strong> (p ≈ 5×10⁻⁷). La distinción entre (a) intención de la práctica [demostrada] y (b) atribución astronómica específica de la gematría tórica [hipótesis] es el núcleo epistémico del trabajo.</p>',
    '<p><strong>What the article DOES claim (with evidence):</strong> <strong>intentional letter engineering</strong> is a historically attested practice (SY, Abulafia, Raziel) and, for the 72-letter verses of Exodus 14:19-21, <strong>empirically improbable by chance</strong> (p ≈ 5×10⁻⁷). The distinction between (a) intention of the practice [demonstrated] and (b) specific astronomical attribution of Toric gematria [hypothesis] is the epistemic core of the work.</p>')
rep('<p><strong>Verificado además (v2.2):</strong> Génesis 1:2 = 3546 → 9999 (repdigit) ✓; Egel 103→404, Ayil 41→55, Shor 506→1111 = 2×253 ✓; Egel+Ayil = 144 ✓; 144×15 = 2160 y 144×180 = 25 920 ✓ (solo a 72 a/°; a 50,29″/año no son enteros); ABBA = AB+BA = 4 = «padre» ✓; 3·7·12−22+1 = 231 = C(22,2) ✓; Éxodo 14:19-21 = 72 letras ×3 ✓.</p>',
    '<p><strong>Also verified (v2.2):</strong> Genesis 1:2 = 3546 → 9999 (repdigit) ✓; Egel 103→404, Ayil 41→55, Shor 506→1111 = 2×253 ✓; Egel+Ayil = 144 ✓; 144×15 = 2160 and 144×180 = 25 920 ✓ (only at 72 y/°; at 50.29″/year they are not integers); ABBA = AB+BA = 4 = "father" ✓; 3·7·12−22+1 = 231 = C(22,2) ✓; Exodus 14:19-21 = 72 letters ×3 ✓.</p>')

# ---- section 19 ----
rep('<h2 id="19-conclusión">19. Conclusión</h2>', '<h2 id="19-conclusión">19. Conclusion</h2>')
rep('<p>El <em>Lector del Cielo</em> convierte el mapeo tripartito del <em>Sefer Yetzirah</em> en un protocolo formal y verificable. La rejilla tropical es medible (λ☉ = 0/90/180/270°); la precesión dota de contenido al 72 (1°/71,58 a) y al 144 (2,01° en 144 a); la sincronía lunar-solar se rige por el 19 (Metón = Saros = basmala) y el 144 (meses del Metón). Los eclipses se rigen por 19, 47 y 223 —no por 37 ni 73, que son los factores de Génesis 1:1—; pero 37 y 73 sí estructuran el año solar civil (365 = 73×5; 2701 pentadas = 37 años), de modo que la gematría del primer verso se refleja en la medida del año: 37 años × 73 pentadas = 2701. Bajo la regla de pertenencia, Génesis 1:1 es legible solo en ventanas de ~13 años que recurren cada ~491 años (sinódico Neptuno–Plutón, fase Aries–Acuario), coincidentes con las grandes re-formaciones religioso-lingüísticas, sobre el fondo precesional de ~2148 años por era. El espejo-palíndromo 2701→3773 es real pero no selectivo; los eclipses no intervienen. El sistema ofrece una base computable y refutable para la intuición de que las eras estelares marcan readaptaciones del lenguaje sagrado, con el 491-años sinódico como motor y el 2148-años precesional como trasfondo.</p>',
    '<p>The <em>Reader of the Sky</em> turns the tripartite mapping of the <em>Sefer Yetzirah</em> into a formal and verifiable protocol. The tropical grid is measurable (λ☉ = 0/90/180/270°); precession gives content to 72 (1°/71.58 y) and to 144 (2.01° in 144 y); lunar–solar synchrony is governed by 19 (Meton = Saros = basmala) and by 144 (the months of Meton). Eclipses are governed by 19, 47, and 223 —not by 37 or 73, which are the factors of Genesis 1:1—; but 37 and 73 do structure the civil solar year (365 = 73×5; 2701 pentads = 37 years), so that the gematria of the first verse is reflected in the measure of the year: 37 years × 73 pentads = 2701. Under the membership rule, Genesis 1:1 is legible only in ~13-year windows that recur every ~491 years (Neptune–Pluto synodic, Aries–Aquarius phase), coincident with the great religious-linguistic re-formations, against the precessional background of ~2148 years per era. The mirror-palindrome 2701→3773 is real but not selective; eclipses play no part. The system offers a computable and refutable basis for the intuition that stellar eras mark readaptations of sacred language, with the 491-year synodic as the engine and the 2148-year precessional as the background.</p>')

# ---- references ----
rep('<h2 id="referencias">Referencias</h2>', '<h2 id="referencias">References</h2>')
rep('<li><em>Sefer Yetzirah</em>. Ed. A. Hayman (2004); trad. A. Kaplan (1990).</li>', '<li><em>Sefer Yetzirah</em>. Ed. A. Hayman (2004); trans. A. Kaplan (1990).</li>')
rep('<li>Sefaria API (corpus Génesis). https://www.sefaria.org/api</li>', '<li>Sefaria API (Genesis corpus). https://www.sefaria.org/api</li>')
rep('<li>Meeus, J. <em>Astronomical Algorithms</em> (ciclos eclipsales: Saros, Inex, Meton; 2.ª ed., 1998).</li>', '<li>Meeus, J. <em>Astronomical Algorithms</em> (eclipse cycles: Saros, Inex, Meton; 2nd ed., 1998).</li>')
rep('<li>Jaspers, K. <em>Vom Ursprung und Ziel der Geschichte</em> (Edad Axial, 1949).</li>', '<li>Jaspers, K. <em>Vom Ursprung und Ziel der Geschichte</em> (Axial Age, 1949).</li>')
rep('<li>Jenkins, V. <em>The Other Bible Code</em> (estructura 37/73 de Génesis 1:1; citada críticamente).</li>', '<li>Jenkins, V. <em>The Other Bible Code</em> (37/73 structure of Genesis 1:1; cited critically).</li>')
rep('<li>Khalifa, R. <em>Computer Manifests the Message</em> (hechos 19-letras/114-azoras; interpretación discutida).</li>', '<li>Khalifa, R. <em>Computer Manifests the Message</em> (19-letters/114-suras facts; disputed interpretation).</li>')
rep('<li>Standish, E. M. / PLAN404 (efeméride planetaria subyacente, Plutón).</li>', '<li>Standish, E. M. / PLAN404 (underlying planetary ephemeris, Pluto).</li>')
rep('<li><em>Libro de los vigilantes</em> (1 Enoc 72–82) y calendario de Qumrán (364 d = 52 semanas); Talmon, S. «Yahadic Fragments».</li>', '<li><em>Book of the Watchers</em> (1 Enoch 72–82) and the Qumran calendar (364 d = 52 weeks); Talmon, S. "Yahadic Fragments".</li>')
rep('<li>Yeivin, I. <em>Introduction to the Tiberian Masorah</em> (recuento masorético de letras/palabras/versos; palabra central <em>darosh darash</em>, Lev 10:16).</li>', '<li>Yeivin, I. <em>Introduction to the Tiberian Masorah</em> (Masoretic count of letters/words/verses; central word <em>darosh darash</em>, Lev 10:16).</li>')
rep('<li><em>Sefer Raziel HaMalakh</em> (Libro del ángel Raziel), ed. M. Margalioth (tratado medieval de permutación de letras y construcción de nombres/ángeles).</li>', '<li><em>Sefer Raziel HaMalakh</em> (Book of the angel Raziel), ed. M. Margalioth (medieval treatise on letter permutation and the construction of names/angels).</li>')
rep('<li>Abulafia, A. <em>Chayei Ha-Olam Ha-Ba</em> / <em>Or Ha-Sekhel</em> (combinación profética de letras, <em>tzerufim</em>); Idel, M. <em>The Mystical Experience in Abraham Abulafia</em>.</li>', '<li>Abulafia, A. <em>Chayei Ha-Olam Ha-Ba</em> / <em>Or Ha-Sekhel</em> (prophetic combination of letters, <em>tzerufim</em>); Idel, M. <em>The Mystical Experience in Abraham Abulafia</em>.</li>')
rep('<li><em>Shem HaMephorash</em> (Nombre de 72): tripletes de Éxodo 14:19-21; tradición en <em>Bahir</em>, <em>Zohar</em> y Abulafia.</li>', '<li><em>Shem HaMephorash</em> (Name of 72): triplets of Exodus 14:19-21; tradition in <em>Bahir</em>, <em>Zohar</em>, and Abulafia.</li>')

# ---- apply prose replacements ----
missing=[]
for a,b in R:
    if a in src: src = src.replace(a,b)
    else: missing.append(a[:70])

# ---- global SVG label replacements (all 5 figures) ----
G = [
    ('>Tauro', '>Taurus'),
    ('>Géminis', '>Gemini'),
    ('>Cáncer', '>Cancer'),
    ('>Escorpio', '>Scorpio'),
    ('>Sagitario', '>Sagittarius'),
    ('>Capricornio', '>Capricorn'),
    ('>Acuario', '>Aquarius'),
    ('>Piscis', '>Pisces'),
    ('>Osa Menor', '>Ursa Minor'),
    ('>Casiopea', '>Cassiopeia'),
    ('>3 madres · eje fijo circumpolar', '>3 mothers · fixed circumpolar axis'),
    ('aria-label="Mapa estelar"', 'aria-label="Star map"'),
    ('>Génesis ✗<', '>Genesis ✗<'),
    ('>Génesis ✓<', '>Genesis ✓<'),
]
gcounts=[]
for a,b in G:
    c = src.count(a)
    src = src.replace(a,b)
    gcounts.append((a, c))

# ---- decimal comma -> dot (digit,digit only) ----
src = re.sub(r'(\d),(\d)', r'\1.\2', src)

io.open('../pdf/lector-del-cielo_EN.html','w',encoding='utf-8').write(src)
print("part5 done; reps:",len(R),"missing:",len(missing))
for m in missing: print("  MISS:",m)
print("SVG label hits:")
for a,c in gcounts: print("  ",a,"->",c)