#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import io
src = io.open('../pdf/lector-del-cielo_EN.html', encoding='utf-8').read()
R = []
def rep(a,b): R.append((a,b))

# ---- section 6 ----
rep('<h2 id="6-los-12-mazzalot-los-animales-del-zodiaco-y-el-tetramorfo">6. Los 12 mazzalot: los animales del zodiaco y el tetramorfo</h2>', '<h2 id="6-los-12-mazzalot-los-animales-del-zodiaco-y-el-tetramorfo">6. The 12 mazzalot: the animals of the zodiac and the tetramorph</h2>')
rep('<p>El zodiaco hebreo (<em>mazzalot</em>) nombra cada signo por un animal u objeto. Estos nombres <strong>son</strong> las figuras que reaparecen en los símbolos religiosos (carnero, becerro, buey, león):</p>',
    '<p>The Hebrew zodiac (<em>mazzalot</em>) names each sign by an animal or object. These names <strong>are</strong> the figures that reappear in religious symbols (ram, calf, ox, lion):</p>')
rep('<th>signo</th><th>letra</th><th>mazzal hebreo</th><th>significado</th>', '<th>sign</th><th>letter</th><th>Hebrew mazzal</th><th>meaning</th>')
rep('<td>Aries</td><td>ה</td><td>טלה <em>Taleh</em></td><td><strong>cordero / carnero</strong></td>', '<td>Aries</td><td>ה</td><td>טלה <em>Taleh</em></td><td><strong>lamb / ram</strong></td>')
rep('<td>Tauro</td><td>ו</td><td>שור <em>Shor</em></td><td><strong>buey / toro</strong></td>', '<td>Taurus</td><td>ו</td><td>שור <em>Shor</em></td><td><strong>ox / bull</strong></td>')
rep('<td>Géminis</td><td>ז</td><td>תאומים <em>Teomim</em></td><td>gemelos</td>', '<td>Gemini</td><td>ז</td><td>תאומים <em>Teomim</em></td><td>twins</td>')
rep('<td>Cáncer</td><td>ח</td><td>סרטן <em>Sartan</em></td><td>cangrejo</td>', '<td>Cancer</td><td>ח</td><td>סרטן <em>Sartan</em></td><td>crab</td>')
rep('<td>Leo</td><td>ט</td><td>אריה <em>Aryeh</em></td><td><strong>león</strong></td>', '<td>Leo</td><td>ט</td><td>אריה <em>Aryeh</em></td><td><strong>lion</strong></td>')
rep('<td>Virgo</td><td>י</td><td>בתולה <em>Betulah</em></td><td>virgen</td>', '<td>Virgo</td><td>י</td><td>בתולה <em>Betulah</em></td><td>virgin</td>')
rep('<td>Libra</td><td>ל</td><td>מאזניים <em>Moznayim</em></td><td>balanza</td>', '<td>Libra</td><td>ל</td><td>מאזניים <em>Moznayim</em></td><td>balance / scales</td>')
rep('<td>Escorpio</td><td>נ</td><td>עקרב <em>Akrav</em></td><td>escorpión</td>', '<td>Scorpio</td><td>נ</td><td>עקרב <em>Akrav</em></td><td>scorpion</td>')
rep('<td>Sagitario</td><td>ס</td><td>קשת <em>Keshet</em></td><td>arco</td>', '<td>Sagittarius</td><td>ס</td><td>קשת <em>Keshet</em></td><td>bow</td>')
rep('<td>Capricornio</td><td>ע</td><td>גדי <em>Gedi</em></td><td>cabrito</td>', '<td>Capricorn</td><td>ע</td><td>גדי <em>Gedi</em></td><td>kid / young goat</td>')
rep('<td>Acuario</td><td>צ</td><td>דלי <em>D\'li</em></td><td>cántaro / cubo</td>', '<td>Aquarius</td><td>צ</td><td>דלי <em>D\'li</em></td><td>pitcher / bucket</td>')
rep('<td>Piscis</td><td>ק</td><td>דגים <em>Dagim</em></td><td>peces</td>', '<td>Pisces</td><td>ק</td><td>דגים <em>Dagim</em></td><td>fishes</td>')
rep('<li><strong>Carnero</strong> = Aries = טלה = letra <strong>ה</strong> (Heh).</li>', '<li><strong>Ram</strong> = Aries = טלה = letter <strong>ה</strong> (Heh).</li>')
rep('<li><strong>Buey / becerro / toro</strong> = Tauro = שור = letra <strong>ו</strong> (Vav).</li>', '<li><strong>Ox / calf / bull</strong> = Taurus = שור = letter <strong>ו</strong> (Vav).</li>')
rep('<li><strong>León</strong> = Leo = אריה = letra <strong>ט</strong> (Tet).</li>', '<li><strong>Lion</strong> = Leo = אריה = letter <strong>ט</strong> (Tet).</li>')
rep('<p>Estas dos letras —<strong>ה (Aries/carnero) y ו (Tauro/buey)</strong>— son precisamente las que aparecen en יהוה (junto a י/Virgo) y en Génesis 1:1. El becerro de oro y el carnero de Abraham son las figuras de las eras taurina y aries (sección 3).</p>',
    '<p>These two letters —<strong>ה (Aries/ram) and ו (Taurus/ox)</strong>— are precisely those that appear in יהוה (together with י/Virgo) and in Genesis 1:1. The golden calf and the ram of Abraham are the figures of the Taurian and Arian eras (section 3).</p>')
rep('<h3 id="6-1-el-tetramorfo-la-cruz-fija">6.1 El tetramorfo = la cruz fija</h3>', '<h3 id="6-1-el-tetramorfo-la-cruz-fija">6.1 The tetramorph = the fixed cross</h3>')
rep('<figcaption><span class="fnum">Fig. 3.</span> La cruz fija: Tauro-Leo-Escorpio-Acuario a 90° exactos (135−45 = 225−135 = 315−225 = 90), imagen geométrica del tetramorfo de Ezequiel 1 / Apocalipsis 4 (buey, león, águila, hombre). Anillos discontinuos señalando los 4 signos fijos.</figcaption>',
    '<figcaption><span class="fnum">Fig. 3.</span> The fixed cross: Taurus-Leo-Scorpio-Aquarius at exact 90° (135−45 = 225−135 = 315−225 = 90), the geometric image of the tetramorph of Ezekiel 1 / Revelation 4 (ox, lion, eagle, man). Dashed rings marking the 4 fixed signs.</figcaption>')
rep('<p>Ezequiel 1 y Apocalipsis 4 describen cuatro seres con caras de <strong>hombre, león, buey y águila</strong>. Corresponden a los <strong>4 signos fijos</strong> del zodiaco (el eje fijo, opuesto al eje cardinal):</p>',
    '<p>Ezekiel 1 and Revelation 4 describe four beings with faces of <strong>man, lion, ox, and eagle</strong>. They correspond to the <strong>4 fixed signs</strong> of the zodiac (the fixed axis, opposite the cardinal axis):</p>')
rep('<th>cara</th><th>signo fijo</th><th>longitud (centro)</th>', '<th>face</th><th>fixed sign</th><th>longitude (center)</th>')
rep('<td>buey</td><td>Tauro (שור)</td><td>45°</td>', '<td>ox</td><td>Taurus (שור)</td><td>45°</td>')
rep('<td>león</td><td>Leo (אריה)</td><td>135°</td>', '<td>lion</td><td>Leo (אריה)</td><td>135°</td>')
rep('<td>águila</td><td>Escorpio (עקרב)</td><td>225°</td>', '<td>eagle</td><td>Scorpio (עקרב)</td><td>225°</td>')
rep('<td>hombre</td><td>Acuario (דלי)</td><td>315°</td>', '<td>man</td><td>Aquarius (דלי)</td><td>315°</td>')
rep('<p><strong>Cálculo:</strong> 135 − 45 = 90; 225 − 135 = 90; 315 − 225 = 90; (45 + 360) − 315 = 90. Los cuatro signos fijos están a <strong>90° exactos</strong> → forman una <strong>cruz cuadrada</strong> (la «cruz fija»), imagen geométrica del tetramorfo. El águila sustituye al escorpión en la tradición exegética (aspecto ascendente del octante escorpión).</p>',
    '<p><strong>Calculation:</strong> 135 − 45 = 90; 225 − 135 = 90; 315 − 225 = 90; (45 + 360) − 315 = 90. The four fixed signs are at <strong>exact 90°</strong> → they form a <strong>square cross</strong> (the "fixed cross"), the geometric image of the tetramorph. The eagle replaces the scorpion in the exegetical tradition (the ascending aspect of the scorpion octant).</p>')
rep('<h3 id="6-2-gematría-de-la-transición-tauro-aries-egel-ayil-shor">6.2 Gematría de la transición Tauro→Aries: Egel, Ayil, Shor</h3>', '<h3 id="6-2-gematría-de-la-transición-tauro-aries-egel-ayil-shor">6.2 Gematria of the Taurus→Aries transition: Egel, Ayil, Shor</h3>')
rep('<p>La transición entre la Era de Tauro y la de Aries (§3) se narra en el éxodo del becerro al carnero. Las tres palabras hebreas —becerro, carnero, toro— tienen gematrías con propiedades aritméticas verificables:</p>',
    '<p>The transition between the Era of Taurus and that of Aries (§3) is narrated in the exodus from the calf to the ram. The three Hebrew words —calf, ram, bull— have gematrias with verifiable arithmetic properties:</p>')
rep('<th>palabra</th><th>hebreo</th><th>letras</th><th>gematría</th><th>+ inverso</th><th>resultado</th>', '<th>word</th><th>Hebrew</th><th>letters</th><th>gematria</th><th>+ reverse</th><th>result</th>')
rep('<td>Becerro</td><td>עגל <em>Egel</em></td><td>ע70 ג3 ל30</td><td>103</td><td>103 + 301</td><td><strong>404</strong> (palíndromo)</td>', '<td>Calf</td><td>עגל <em>Egel</em></td><td>ע70 ג3 ל30</td><td>103</td><td>103 + 301</td><td><strong>404</strong> (palindrome)</td>')
rep('<td>Carnero</td><td>איל <em>Ayil</em></td><td>א1 י10 ל30</td><td>41</td><td>41 + 14</td><td><strong>55</strong> (repdigit)</td>', '<td>Ram</td><td>איל <em>Ayil</em></td><td>א1 י10 ל30</td><td>41</td><td>41 + 14</td><td><strong>55</strong> (repdigit)</td>')
rep('<td>Toro</td><td>שור <em>Shor</em></td><td>ש300 ו6 ר200</td><td>506</td><td>506 + 605</td><td><strong>1111</strong> (repdigit)</td>', '<td>Bull</td><td>שור <em>Shor</em></td><td>ש300 ו6 ר200</td><td>506</td><td>506 + 605</td><td><strong>1111</strong> (repdigit)</td>')
rep('<p><strong>Suma de la transición:</strong> Egel + Ayil = 103 + 41 = <strong>144</strong> (el ídolo que termina + el símbolo que comienza = 144; véase §14).</p>',
    '<p><strong>Sum of the transition:</strong> Egel + Ayil = 103 + 41 = <strong>144</strong> (the idol that ends + the symbol that begins = 144; see §14).</p>')
rep('<p><strong>Shor y el alfabeto:</strong> suma(1..22) = 22·23/2 = <strong>253</strong> (triangular de 22, las 22 letras). Y 253 × 2 = <strong>506 = Shor</strong>. El nombre hebreo de Tauro equivale al doble de la suma de las 22 letras —el «alfabeto duplicado» (cielo y tierra) del SY—.</p>',
    '<p><strong>Shor and the alphabet:</strong> sum(1..22) = 22·23/2 = <strong>253</strong> (the 22nd triangular, the 22 letters). And 253 × 2 = <strong>506 = Shor</strong>. The Hebrew name of Taurus equals twice the sum of the 22 letters —the "duplicated alphabet" (heaven and earth) of the SY—.</p>')
rep('<p><strong>Génesis 1:2:</strong> gematría = 3546; 3546 + 6453 = <strong>9999</strong> (repdigit de 4 cifras), verificable en el corpus Sefaria.</p>',
    '<p><strong>Genesis 1:2:</strong> gematria = 3546; 3546 + 6453 = <strong>9999</strong> (4-digit repdigit), verifiable in the Sefaria corpus.</p>')
rep('<blockquote><strong>Aritmética real, interpretación acotada.</strong> Todas las sumas anteriores son exactas. <strong>La propiedad de palíndromo-espejo por sí sola no es un checksum selectivo</strong> (§13.1): el <strong>47,9 %</strong> de las 6045 raíces del lexicón y el <strong>58 %</strong> de los <em>mazzalot</em> son ya palíndromo-espejo —base alta de la gematría decimal—. Lo específico (no trivial) de estas tres palabras no es el palíndromo, sino las <strong>sumas con significado astronómico</strong> (Egel+Ayil = 144; Shor = 2×suma(1..22)). Ahora bien: la <strong>intencionalidad de la práctica</strong> de diseñar lenguaje por reglas de letras <strong>sí está atestada históricamente</strong> (§6.3), y para los versos de 72 letras, <strong>demostrada empíricamente</strong>. Lo que permanece como hipótesis (no falsado, no probado estadísticamente) es la atribución astronómica <em>específica</em> de la gematría tórica (2701 = 37×73 ↔ era; 144 ↔ transición): consistente con la tradición atestada, pero el método del palíndromo no la confirma (base 48 %) y no existe nulo para «números con significado».</blockquote>',
    '<blockquote><strong>Real arithmetic, bounded interpretation.</strong> All the above sums are exact. <strong>The mirror-palindrome property by itself is not a selective checksum</strong> (§13.1): <strong>47.9 %</strong> of the 6045 roots of the lexicon and <strong>58 %</strong> of the <em>mazzalot</em> are already mirror-palindromes —high base of decimal gematria—. What is specific (non-trivial) to these three words is not the palindrome, but the <strong>sums with astronomical meaning</strong> (Egel+Ayil = 144; Shor = 2×sum(1..22)). Now then: the <strong>intentionality of the practice</strong> of designing language by letter rules <strong>is historically attested</strong> (§6.3), and for the 72-letter verses, <strong>empirically demonstrated</strong>. What remains a hypothesis (not falsified, not statistically proven) is the <em>specific</em> astronomical attribution of Toric gematria (2701 = 37×73 ↔ era; 144 ↔ transition): consistent with the attested tradition, but the palindrome method does not confirm it (48 % base) and there is no null for "numbers with meaning".</blockquote>')
rep('<h3 id="6-3-ingeniería-intencional-de-letras-las-231-puertas-abba-y-">6.3 Ingeniería intencional de letras: las 231 puertas, ABBA y el Nombre de 72</h3>', '<h3 id="6-3-ingeniería-intencional-de-letras-las-231-puertas-abba-y-">6.3 Intentional letter engineering: the 231 gates, ABBA, and the Name of 72</h3>')
rep('<p>La hipótesis de un <strong>diseño intencional del lenguaje hebreo por reglas de letras</strong> no es una inferencia estadística: es una <strong>práctica documentada</strong>. Las fuentes son verificables:</p>',
    '<p>The hypothesis of an <strong>intentional design of the Hebrew language by letter rules</strong> is not a statistical inference: it is a <strong>documented practice</strong>. The sources are verifiable:</p>')
rep('<p>*<em>1. Las 231 puertas del </em>Sefer Yetzirah<em> (cap. 2).<strong> De 22 letras, las combinaciones de 2 sin repetición = C(22,2) = </strong>22×21/2 = 231 puertas<strong> (שערים). El SY ordena explícitamente permutarlas: AB y BA, AG y GB… La </strong>primera puerta<strong> es AB (אב, = 3); su </strong>espejo<strong> es BA (בא, = 3); concatenadas, </strong>AB+BA = ABBA (אבא) = 4 = «padre» (arameo), palíndromo</em><em>. La operación inicial del SY produce, por simetría especular, la palabra «padre»: </em>como arriba es abajo<em> (AB ↔ BA). Añadiendo el teónimo EL: <strong>AB-EL = אבאל = 34</strong> (Abiel); <strong>BA-AL = בעל = 102</strong> (Baal, «señor»). El método de sufijación (triplete + EL/YAH) es el del </em>Shem HaMephorash*.</p>',
    '<p>*<em>1. The 231 gates of the </em>Sefer Yetzirah<em> (ch. 2).<strong> From 22 letters, the combinations of 2 without repetition = C(22,2) = </strong>22×21/2 = 231 gates<strong> (שערים). The SY explicitly orders them to be permuted: AB and BA, AG and GB… The </strong>first gate<strong> is AB (אב, = 3); its </strong>mirror<strong> is BA (בא, = 3); concatenated, </strong>AB+BA = ABBA (אבא) = 4 = "father" (Aramaic), a palindrome</em><em>. The initial operation of the SY produces, by mirror symmetry, the word "father": </em>as above so below<em> (AB ↔ BA). Adding the theonym EL: <strong>AB-EL = אבאל = 34</strong> (Abiel); <strong>BA-AL = בעל = 102</strong> (Baal, "lord"). The suffixing method (triolet + EL/YAH) is that of the </em>Shem HaMephorash*.</p>')
rep('<p><strong>2. Coherencia interna 3-7-12 → 231.</strong> La propia estructura tripartita del SY genera su número de puertas: <strong>3·7·12 − (3+7+12) + 1 = 252 − 22 + 1 = 231 = C(22,2)</strong>. Las cuentas de madres/dobles/simples reproducen el número de puertas: el sistema es numéricamente autocoherente.</p>',
    '<p><strong>2. Internal coherence 3-7-12 → 231.</strong> The very tripartite structure of the SY generates its number of gates: <strong>3·7·12 − (3+7+12) + 1 = 252 − 22 + 1 = 231 = C(22,2)</strong>. The counts of mothers/doubles/simples reproduce the number of gates: the system is numerically self-coherent.</p>')
rep('<p><strong>3. El Nombre de 72 y los versos de 72 letras (Éxodo 14:19-21).</strong> El <em>Shem HaMephorash</em> se construye con los 72 tripletes leídos en columna sobre tres versos consecutivos del Éxodo. <strong>Verificación contra el texto masorético (Sefaria):</strong> Éxodo 14:19 = <strong>72</strong> letras consonánticas; 14:20 = <strong>72</strong>; 14:21 = <strong>72</strong> (216 en total → 72 tripletes). En el Génesis, solo el <strong>0,78 %</strong> de los versos tienen exactamente 72 consonantes (media 51,1); la probabilidad de <strong>tres versos consecutivos</strong> con exactamente 72 por azar es ≈ (0,0078)³ ≈ <strong>5×10⁻⁷</strong>. <strong>Esto es ingeniería intencional de versos, empíricamente verificada</strong>, no inferencia.</p>',
    '<p><strong>3. The Name of 72 and the 72-letter verses (Exodus 14:19-21).</strong> The <em>Shem HaMephorash</em> is built with the 72 triplets read in columns over three consecutive verses of Exodus. <strong>Verification against the Masoretic text (Sefaria):</strong> Exodus 14:19 = <strong>72</strong> consonantal letters; 14:20 = <strong>72</strong>; 14:21 = <strong>72</strong> (216 in total → 72 triplets). In Genesis, only <strong>0.78 %</strong> of verses have exactly 72 consonants (mean 51.1); the probability of <strong>three consecutive verses</strong> with exactly 72 by chance is ≈ (0.0078)³ ≈ <strong>5×10⁻⁷</strong>. <strong>This is intentional verse engineering, empirically verified</strong>, not inference.</p>')
rep('<p><strong>4. La tradición del método.</strong> Abraham Abulafia (1240–1291) codificó la combinación profética de letras (<em>tzerufim</em>); el <em>Sefer Raziel HaMalakh</em> (libro del ángel Raziel) es un tratado medieval de construcción de nombres y ángeles por permutación de letras. La <strong>práctica</strong> de diseñar lenguaje sagrado por reglas combinatorias está, pues, documentada y continuada durante milenios.</p>',
    '<p><strong>4. The tradition of the method.</strong> Abraham Abulafia (1240–1291) codified the prophetic combination of letters (<em>tzerufim</em>); the <em>Sefer Raziel HaMalakh</em> (book of the angel Raziel) is a medieval treatise on the construction of names and angels by permutation of letters. The <strong>practice</strong> of designing sacred language by combinatorial rules is, then, documented and continued for millennia.</p>')
rep('<blockquote><strong>Síntesis sobre la intencionalidad.</strong> Hay dos argumentos distintos: (a) <strong>estadístico</strong> —el palíndromo-espejo como sello— que <strong>no</strong> discrimina (base 48 %, §13.1); y (b) <strong>metodológico-histórico</strong> —la existencia de una tradición atestada y, para los 72 versos, de una construcción empíricamente improbable (p ≈ 5×10⁻⁷)— que <strong>sí</strong> demuestra que la ingeniería intencional de letras es una práctica real. El <em>Lector del Cielo</em> se sitúa en esta tradición: opera el mapeo SY como un protocolo, y la pregunta de si la gematría tórica codifica astronomía es una <strong>hipótesis dentro de una tradición atestada</strong>, no una afirmación aislada. (La fuente <em>Domination Codex</em> cita la misma aritmética —231, factoriales, ABBA, Abulafia— pero no aporta tests nulos; es tradición hermenéutica, no prueba estadística.)</blockquote>',
    '<blockquote><strong>Synthesis on intentionality.</strong> There are two distinct arguments: (a) <strong>statistical</strong> —the mirror-palindrome as a seal— which does <strong>not</strong> discriminate (48 % base, §13.1); and (b) <strong>methodological-historical</strong> —the existence of an attested tradition and, for the 72 verses, of an empirically improbable construction (p ≈ 5×10⁻⁷)— which <strong>does</strong> demonstrate that intentional letter engineering is a real practice. The <em>Reader of the Sky</em> situates itself in this tradition: it operates the SY mapping as a protocol, and the question of whether Toric gematria encodes astronomy is a <strong>hypothesis within an attested tradition</strong>, not an isolated claim. (The <em>Domination Codex</em> source cites the same arithmetic —231, factorials, ABBA, Abulafia— but provides no null tests; it is hermeneutical tradition, not statistical proof.)</blockquote>')

missing=[]
for a,b in R:
    if a in src: src = src.replace(a,b)
    else: missing.append(a[:70])
io.open('../pdf/lector-del-cielo_EN.html','w',encoding='utf-8').write(src)
print("part3 done; reps:",len(R),"missing:",len(missing))
for m in missing: print("  MISS:",m)